<template>
  <v-container>
    <v-row>
      <v-col sm="12"
             class="d-flex justify-space-around"
      >
        <v-img
          :src="require('../assets/festival_big2.png')"
          max-width="1050"

        ></v-img>
      </v-col>
      <v-col sm="12"
             class="d-flex justify-space-around">
        <v-expansion-panels
          max-width="1050">
          <v-expansion-panel>
            <v-expansion-panel-header
              v-slot="{ open } "
              color="cyan darken-2"
              class="white--text"
            >
              <v-row>
                <v-col cols="12" class="text-center">
                  <h3 v-if="!open">
                    搜尋
                    <v-icon color="white">add_circle_outline</v-icon>
                  </h3>
                  <h3 v-else>
                    關閉
                    <v-icon color="white">cancel</v-icon>
                  </h3>
                </v-col>
                <v-col
                  cols="12"
                >
                  <v-fade-transition leave-absolute>
                    <v-row
                      no-gutters
                      style="width: 100%"
                      v-if="!open"
                    >
                      <v-col cols="3">
                        關鍵字: {{ form.keyword }}
                      </v-col>
                      <v-col cols="5">
                        活動日期範圍:
                        {{ form.start }}{{ form.end && ' ~ ' }}{{ form.end }}
                      </v-col>
                      <v-col cols="4">
                        地點: {{ form.location || '' }}
                      </v-col>
                    </v-row>
                  </v-fade-transition>
                </v-col>
              </v-row>
            </v-expansion-panel-header>
            <v-expansion-panel-content
              color="grey lighten-3"
            >
              <v-row
                justify="space-around"
              >
                <v-col cols="4" align-self="center">
                  <h4>活動關鍵字</h4>
                </v-col>
                <v-col cols="8">
                  <v-text-field
                    v-model="form.keyword"
                    label="活動關鍵字"
                  ></v-text-field>
                </v-col>
                <v-col cols="4" align-self="center">
                  <h4>活動日期範圍</h4>
                </v-col>
                <v-col cols="4">
                  <v-menu
                    ref="startMenu"
                    :close-on-content-click="false"
                    :return-value.sync="form.start"
                    offset-y
                    min-width="290px"
                  >
                    <template v-slot:activator="{ on, attrs }">
                      <v-text-field
                        v-model="form.start"
                        label="開始日期"
                        readonly
                        v-bind="attrs"
                        v-on="on"
                        clearable
                      ></v-text-field>
                    </template>
                    <v-date-picker
                      v-model="date"
                      no-title
                      scrollable
                    >
                      <v-spacer></v-spacer>
                      <v-btn
                        text
                        color="grey"
                        @click="$refs.startMenu.isActive = false"
                      >
                        Cancel
                      </v-btn>
                      <v-btn
                        text
                        color="primary"
                        @click="$refs.startMenu.save(date)"
                      >
                        OK
                      </v-btn>
                    </v-date-picker>
                  </v-menu>
                </v-col>
                <v-col cols="4">
                  <v-menu
                    ref="endMenu"
                    :close-on-content-click="false"
                    :return-value.sync="form.end"
                    offset-y
                    min-width="290px"
                  >
                    <template v-slot:activator="{ on, attrs }">
                      <v-text-field
                        v-model="form.end"
                        label="結束日期"
                        readonly
                        v-bind="attrs"
                        v-on="on"
                        clearable
                      ></v-text-field>
                    </template>
                    <v-date-picker
                      v-model="date"
                      no-title
                      scrollable
                      locale="zh-cn"
                    >
                      <v-spacer></v-spacer>
                      <v-btn
                        text
                        color="grey"
                        @click="$refs.endMenu.isActive = false"
                      >
                        Cancel
                      </v-btn>
                      <v-btn
                        text
                        color="primary"
                        @click="$refs.endMenu.save(date)"
                      >
                        OK
                      </v-btn>
                    </v-date-picker>
                  </v-menu>
                </v-col>
                <v-col cols="2" align-self="center">
                  <h4>地區</h4>
                </v-col>
                <v-col cols="10">
                  {{ form.location }}
                  <v-row>
                    <v-col xl="1" md="2" sm="3" xs="4"
                           v-for="item in locations"
                           v-bind:key="item">
                      <v-checkbox
                        class="mt-0"
                        v-model="form.location"
                        :label="item"
                        :value="item"
                      />
                    </v-col>
                  </v-row>
                </v-col>
                <v-col cols="12">
                  <v-btn
                    color="cyan darken-2"
                    dark
                  >
                    搜尋
                  </v-btn>
                  <v-btn
                    color="grey"
                    dark
                  >
                    清除
                  </v-btn>
                </v-col>
              </v-row>
            </v-expansion-panel-content>
          </v-expansion-panel>
        </v-expansion-panels>
      </v-col>
      <v-col sm="12"
             v-for="item in festivalList"
             :key="item.actId"
      >
        <Festival :festival="item"></Festival>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import Festival from './Festival';

export default {
  name: 'FestivalPage',
  components: { Festival },
  data: () => ({
    date: null,
    form: {
      keyword: null,
      start: null,
      end: null,
      location: [],
    },
    locations: ['臺北市', '基隆市', '新北市', '宜蘭縣', '桃園市', '新竹市', '新竹縣', '苗栗縣', '臺中市', '彰化縣', '南投縣', '雲林縣', '嘉義縣', '嘉義市', '臺南市', '高雄市', '屏東縣', '澎湖縣', '花蓮縣', '台東縣', '金門縣', '連江縣'],
    festivalList: [
      {
        actId: 419,
        actName: '2021臺北白晝之夜',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '「Nuit Blanche 白晝之夜」是全球的夜間城市藝術祭，2002年創始於法國巴黎，在10月第一個週六跨夜舉行。「白晝之夜」根基於「都市創新」及「公共空間設計」兩大核心概念，為市民提供親近藝術及城市的場域。「白晝之夜」有三大特色：「跨夜舉辦」、「免費參加」及「公民參與」，透過多樣化的藝術作品及演出安排，讓人自然接觸藝術，自由穿梭於城市空間之中。「白晝之夜」打破大眾娛樂與純藝術的界線，作品橫跨劇場、馬戲、舞蹈、音樂、行為藝術、新媒體藝術等不同領域，讓跨文化、跨世代的多樣美學交錯混融。「白晝之夜」在城市中塑造獨特的交流共享環境，透過藝術轉化都市空間，讓整個臺北市化身一夜限定的大型美術館。\r\n「2021年臺北白晝之夜」定於10/2(六)傍晚6時啟動至10/3(日)清晨6時，在全球面臨疫情撼動的時刻，展開「重新思辨」，透過晝夜的雙⾯哲思啟發，解構重組⽩晝之夜，將交流現場的共感精神，以虛實互聯體驗聚合起來，帶來全新的 2021臺北⽩晝之夜「線上感 Interoperability」。 --\u003e',
        participation: '',
        cityId: 111,
        address: '臺北市 南港區南港車站',
        tel: '',
        org: '臺北市政府文化局',
        startTime: 'Oct 2, 2021 12:00:00 AM',
        endTime: 'Oct 3, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '25.0523151',
        latitude: '121.6052852',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  南港區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080492/a7714b27db84ed326df3863e94ba351db463d527.jpg',
      },
      {
        actId: 414,
        actName: '2021三義木雕藝術節系列活動',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '2021三義木雕藝術節系列活動，推動在地產業與文化觀光結合，型塑嶄新的「慢活」的三義慢城意象，讓更多人再次看見三義。透過三義木雕藝術節活動行銷推廣，融合傳統工藝文化、表演藝術演出，展現地方獨特風采，同時串聯在地社區與觀光休閒產業，為三義整體觀光魅力加分，提高地方能見度，增加文化知名度，打造整體慢城氛圍。\r\n\r\n    臺灣國際木雕裝置藝術大展：07/20-10/17\r\n    木藝慢活嘉年華：10/08-10/11\r\n',
        participation: '',
        cityId: 816,
        address: '苗栗縣 三義鄉廣盛村廣聲新城88號',
        tel: '',
        org: '苗栗縣政府文化觀光局',
        startTime: 'Oct 8, 2021 12:00:00 AM',
        endTime: 'Oct 11, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://wood.mlc.gov.tw/',
        longitude: '24.4059435',
        latitude: '120.7609731',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '苗栗縣  三義鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080487/a47516cfd2780b2e75b40189bc45bcc46cae1de7.jpg',
      },
      {
        actId: 398,
        actName: '2021一見雙雕藝術季',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '一見雙雕藝術季結合創意鹽產品、鹽業文化與沙灘水域風情，於2012年起將轄內「鹽」與「沙」兩大觀光資源整合，透過鹽與沙的藝術作品與觀光旅遊活動激盪新火花，展現雲嘉南觀光新「粒」量，充滿創新的雲嘉南濱海觀光新體驗，實質帶動周邊觀光產業之發展，形塑「南鹽雕、北沙雕」之活動品牌。\r\n為強化西南濱海獨有的鹽業文化風情，自2019年起轉型為「鹽雕+光雕」，結合靜態「鹽雕」作品展、動態影音「光雕」秀等吸睛工藝手法，打造鹽業文化絢麗的視覺藝術饗宴。2021年進一步嘗試結合在地的「鹽」與「漂流木」兩種材料，以永續再生的環保理念，規劃鹽雕與漂流木雕地景藝術展，將雲嘉南在地特色與藝術融為一體，為遊客獻上一場不同以往的一見雙雕藝術饗宴。\r\n\r\n    鹽雕－七股鹽山8/11開展\r\n    漂流木雕地景藝術－馬沙溝海洋休閒運動渡假中心8/21開展\r\n',
        participation: '',
        cityId: 1622,
        address: '臺南市 七股區七股鹽山',
        tel: '',
        org: '交通部觀光局雲嘉南濱海國家風景區管理處',
        startTime: 'Aug 11, 2021 12:00:00 AM',
        endTime: 'Oct 11, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://swcoast-nsa.travel/zh-tw',
        longitude: '23.1541259',
        latitude: '120.0999988',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺南市  七股區(七股鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080470/85ed52d587e53dbeb781c53397e5410fcd42a7d2.jpg',
      },
      {
        actId: 406,
        actName: '2021大稻埕情人節',
        levelName: '全國級',
        grade1: '浪漫',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '為慶祝七夕情人節，每年農曆七夕前周末於大稻埕周邊舉辦以情人為主題之煙火音樂展演活動，為全臺最經典之七夕情人慶典。2019年活動以「萬人一起唱情歌」為主題，除了歌手團體接力演出一首首情歌，並將施放情人煙火秀，現場還有浪漫花牆、愛情塗鴉牆、愛情文創市集、胖卡美食、清涼啤酒專區與有趣的體驗活動，並與北門相機商圈合作推出「大稻埕情人節攝影比賽」，歡迎你(妳)帶著情人或家人、朋友一起來大稻埕河岸享受浪漫的時光。\r\n本活動並結合在地商圈及產業推出前期活動，及與旅行社合作打造專屬遊程，邀請民眾走進街區，漫步臺北舊城區巷弄間，細細體會大稻埕經典小鎮魅力。\r\n※ 受疫情影響，2021大稻埕情人節煙火秀，將延期至10月16日舉辦。',
        participation: '',
        cityId: 102,
        address: '臺北市 大同區延平河濱公園',
        tel: '',
        org: '臺北市政府觀光傳播局',
        startTime: 'Oct 16, 2021 12:00:00 AM',
        endTime: 'Oct 16, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '25.054116',
        latitude: '121.507081',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  大同區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080478/5aed024339b76131ac931de7090cef3aea994c3d.jpg',
      },
      {
        actId: 423,
        actName: '2021臺北國際賞鳥博覽會',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '本活動107年從野鳥保育觀點規劃活動，分為十大主題\u0026mdash;「主題闖關遊戲」、「NGO 地球村」、「生態小劇場」、「地方創生市集」、「二十年博覽會回顧」、「野望放映室」、「濕地交流工作坊」、「賞鳥補給站」、「VR 鳥瞰體驗」、「自然藝術」，邀請國內外保育團體透過攤位展示、闖關集章遊戲、DIY 活動、手偶戲劇演出、講座及影片放映等方式介紹生態知識及賞鳥體驗，希望藉由交流自然棲地及環境守護、自然觀察體驗等， 讓大人孩童皆能由淺入深看。',
        participation: '',
        cityId: 109,
        address: '臺北市 北投區關渡路55號',
        tel: '',
        org: '社團法人台北市野鳥學會',
        startTime: 'Oct 16, 2021 12:00:00 AM',
        endTime: 'Oct 17, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.wbst.org.tw/',
        longitude: '25.1188989',
        latitude: '121.4707983',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  北投區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080496/4867074a92bf4bf88c06e11d134c10c52822028c.jpg',
      },
      {
        actId: 427,
        actName: '2021太魯閣峽谷音樂節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '太魯閣峽谷的壯闊山河名聞於世，崖壁峭立，景緻清幽，也是孕育園區內豐富獨特的自然生態、人文景觀重要的搖籃。重新思考人與自然相處之道成為國家公園重要的課題，除了為旅人們呈現知性的太魯閣，也試圖為峽谷營造多向度的藝文空間意象。擬透過原住民族歌曲及舞蹈、弦樂團、管弦樂團及流行歌曲演唱，以古典與現代的多元融合樂音呈現太魯閣豐富的生態。賦與峽谷地景更生動的表情，透過聲音在層巒疊翠的山谷之間迴盪，與山河融會交織，爆發出純粹動人的能量，展現太魯閣峽谷數百萬年來的生命淬煉。期能引領民眾體會自然山水、萬物和人之間的生命力量，提升人文與自然素養，並活絡花蓮鄰近地區遊憩活動與經濟。\r\n※因應隨時變化的疫情，守住全民防疫成果，太管處經審慎評估後，將今年的峽谷音樂節展延到明年疫情穩定後再舉辦，明年舉辦時間暫定為111年10月22日（星期六）。',
        participation: '',
        cityId: 2303,
        address: '花蓮縣 秀林鄉太魯閣臺地',
        tel: '',
        org: '太魯閣國家公園管理處',
        startTime: 'Oct 23, 2021 12:00:00 AM',
        endTime: 'Oct 23, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: 'https://www.taroko.gov.tw/',
        longitude: '24.1583106',
        latitude: '121.6212098',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '花蓮縣  秀林鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080500/161546f83393c9d54a11e805b3eabc0f46e11171.jpg',
      },
      {
        actId: 356,
        actName: '2021東海岸大地藝術節暨月光・海音樂會',
        levelName: '國際級',
        grade1: '浪漫',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '東海岸大地藝術節（TECLandArt Festival）是交通部東部海岸國家風景管理處於2015年開始委託專業承辦，沿著台灣東海岸各地舉辦的藝術活動，內容包括邀請藝術家駐地創作大型戶外作品，並設置在東海岸沿途風景區，稱之為「駐地創作營」。除此之外，還有沿著台11線公路開放藝術工作室、藝術市集、音樂會等，是一個以東部海岸線區域的自然環境、部落生活、棲息居住、旅行壯遊為主題的藝術節。東部海岸壯闊自然，有時優美有時狂野，有時神秘有時開放，生活在其中的人們，寂靜而自然，樸素而自由，本藝術節透過駐地創作、藝術品設置、藝術活動、完善的旅行設施，讓觀光者在公共場所中找到情境涉入與幸福感之關係，繼而產生夢想的在地生根。\r\n※交通部觀光局東部海岸國家風景區管理處主辦的「2021東海岸大地藝術節」，原全數取消的「月光\u0026middot;海音樂會」，因應近期疫情趨緩穩定，疫情警戒調降為二級，為回應眾多粉絲樂迷敲碗期待的心聲，將規劃辦理一場次的線上「月光\u0026middot;海音樂會」，歡迎大家鎖定東海岸大地藝術節YouTube頻道，一同線上搖擺。詳情請至東海岸大地藝術節活動網站查詢。\r\n2021月光．海音樂會場次：\r\n\r\n    7/22（四）夏至之島，希望之歌  //夏至場//\r\n    \r\n    7/23（五）島嶼之母，海洋之子\r\n    7/24（六）山海匯流   //售票場次//\r\n    8/22（日）曙光與月光共舞\r\n    8/23（一）山海唱和，萬物皆音\r\n    9/21（二）蹽溪過嶺，向海光  //中秋場//\r\n    9/22（三）海歌山和，愛綿延\r\n\r\n',
        participation: '',
        cityId: 2211,
        address: '臺東縣 成功鎮新村路25號',
        tel: '',
        org: '交通部觀光局東部海岸國家風景區管理處',
        startTime: 'Jul 22, 2021 12:00:00 AM',
        endTime: 'Oct 30, 2021 12:00:00 AM',
        cycle: '9月22日舉辦線上「月光·海音樂會」',
        noncycle: '',
        website: 'https://www.teclandart.tw/zh/home/',
        longitude: '23.0198445',
        latitude: '121.3242585',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺東縣  成功鎮',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080422/b5363f4cd261d79a0355088ecbe393758bc0bd66.jpg',
      },
      {
        actId: 417,
        actName: '2021臺中爵士音樂節',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '臺中爵士音樂節從2003年開辦以來，以自由即興的風格展現多元的音樂型式，呼應臺中市輕鬆、悠閒的都會生活文化特色，再加上本系列活動辦理地點除市民廣場、草悟道以外，並擴及其他展演空間、百貨商圈及學校等據點，透過開放空間的展演活動，吸引眾多市民、外縣市民眾及外籍人士、觀光客等共同參與活動，不但為臺中市營造令人印象深刻的文化生活氛圍，吸引民眾參與戶外藝術休閒活動，更帶動週邊商業與休閒旅遊產業的發展，透過逐年累積交流成果及活動效益，使本項活動逐漸成為臺中市最具吸引力的國際文化節慶活動，並成為和東京、曼谷、首爾等城市並列的亞洲四大爵士音樂節之一。\r\n每年臺中爵士音樂節皆延續國際性、豐富性與多樣性的活動特色，研擬不同主題，延攬國際重量級的爵士樂團前來演出，打造臺中城市知名度，過去逾16年共引介來自全球5大洲超過600名國外樂手來臺演出，總表演場次更逾500場。當中並加強與國際城市、辦事處、國外樂團聯繫，邀請更多優良爵士樂團參與演出，廣納全國爵士樂高手與國際團隊交流，並藉地利之便，對當地宣傳臺中爵士音樂節，達到文化交流的目的，進而建立合作機制、創造雙贏局面。此外，在各縣市競相以活動行銷方式推展地方特色，帶動觀光產業，中部地區溫暖的氣候及充滿氛圍的步調、建立既有特色又能與國際接軌的文化活動，創造出有別於一般活動的行銷機制，結合大臺中地區觀光旅遊、特產及文化等地方產業共同行銷，成功的將臺中市推上全國甚至全世界的舞臺。',
        participation: '',
        cityId: 1004,
        address: '臺中市 西區2021年活動地點尚未確定',
        tel: '',
        org: '臺中市政府文化局',
        startTime: 'Oct 22, 2021 12:00:00 AM',
        endTime: 'Oct 30, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '24.1477718',
        latitude: '120.6736565',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺中市  西區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080490/e8906a1c4a5426732ee7715ef654b49f820d7b5f.jpg',
      },
      {
        actId: 418,
        actName: '新竹市玻璃設計藝術節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '新竹地區玻璃產業發展已有90餘年，每兩年藉由玻璃藝術節的辦理，突顯地方特色。整合產業、文化與觀光等資源，推動玻璃產業之發展，為文化創意產業挹注新活力，帶動本市經濟繁榮。2020新竹市玻璃設計藝術節邁入第13屆，以新竹、設計、公園、城市及藝術等元素策劃。本次活動包括主題特展，金玻獎比賽、假日表演與市集等活動，將玻璃帶入生活，結合藝術、設計與文化，內容多元豐富。我們將以玻璃藝術增添公園的藝術氛圍與場景，透過公園美景自然融入生活藝術作品，開創另一個嶄新的、藝術的新竹公園。',
        participation: '',
        cityId: 6,
        address: '新竹市 東區東大路一段2號',
        tel: '',
        org: '新竹市政府',
        startTime: 'Sep 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: '',
        longitude: '24.801203',
        latitude: '120.978137',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新竹市',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080491/03f44e0d405a3a82f76d0e95f4b4f106a5911e83.jpg',
      },
      {
        actId: 415,
        actName: '高雄左營萬年季',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '每年10月中旬在左營蓮池潭登場的萬年季活動，自2001年舉辦至今已邁入第20年，運用左營獨有天然景觀（蓮池潭及周邊林立的寺廟）、結合特殊民情風俗（攻炮城、迓火獅）等在地因素規劃而成，由於活動設計極具地方特色，每年吸引許多參觀人潮，已發展成為本市重要民俗文化觀光節慶活動。',
        participation: '',
        cityId: 1811,
        address: '高雄市 左營區蓮潭路',
        tel: '',
        org: '高雄市政府民政局',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '22.685221',
        latitude: '120.295485',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '高雄市  左營區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080488/633e7f0dd2309bdd4e08db4e097db5b25fd007c4.jpg',
      },
      {
        actId: 421,
        actName: '2021南投世界茶業博覽會',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '美食',
        grade6: '',
        description: '2019年南投世界茶業博覽會邁入第10年，每年創下優異的營業額，近年與台灣工藝研究發展中心合作並將縣內之茶、竹產業、茶竹文化與創意商品等作行銷宣傳與推廣，藉由活動，不只在創造商機、增加農民的收入，並帶動周邊及整體觀光產業；讓傳統農業轉型，加強品牌行銷，增加市場的競爭力，讓茶與竹之文化創意商品化；茶道與竹藝融合，同時以世界博覽會的形式，展售各國的特色茶樣，展示南投的竹工藝術，呈現多元茶與竹文化，進而塑造出世界台灣島的精神，提高台灣茶葉的曝光率與知名度。\r\n眾所期待的千人茶會、千人揉茶、茶與音樂，還有茶薰六覺，亦在大操場或樹蔭下自然呈現。在黃金品茗館裡，可以品飲到來自台灣各地比賽茶的特等茶。中興會堂及青少年活動中心同時邀請中、日、韓等世界各地的茶道展演，使與會的民眾能對國際茶文化、茶產業能有更廣大的認識視野。\r\n主題展館涵蓋有世界茶葉之旅、見證台灣茶的茶葉藝文館、黃金品茗館外，今年加入了農村再生館、客家產業館等再地的產業融入不同的文化、特色增加活動精彩度。',
        participation: '',
        cityId: 1201,
        address: '南投縣 南投市中興新村 中興會堂',
        tel: '',
        org: '南投縣政府',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: '',
        longitude: '23.9492923',
        latitude: '120.6962211',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '南投縣  南投市',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080494/df8e22d3737c3bb5f33f348591c47a61e7d5a824.jpg',
      },
      {
        actId: 422,
        actName: '2021桃園國際風箏節',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '大溪，以大漢溪名為地名，顯示出大漢溪在此區的發展扮演著重要的角色。早期大漢溪水源豐沛深可行船，順流而下孕育了河川右岸的貿易、木材產業；滋養了河川左岸水稻、韭菜產業，展現大溪的水與在地人民有著共存共榮的關係。\r\n大漢溪左岸的中庄地區，因水源保護區而低度開發，河階地勢關係，每年秋季的東北季風穩而風力強，相當適合施放風箏！中庄調整池是一個平面水庫，為板新淨水廠的備用水庫來源，同時亦為景觀池，於2017年竣工，外型像把大提琴，環境優美。景觀土丘則是利用中庄調整池餘方回填，經過綠美化工程，形成一個4.5公頃一望無際的大草坪，非常適合放風箏及舉行各式運動的多功能場所。\r\n乘風飛翔的風箏運動，正是低碳觀光的最佳展現！2018年開始桃園市政府為活化景觀土丘，邀請國內外風箏團隊表演大型主題特色風箏、特技風箏，讓翱翔天際的繽紛風箏成為大溪獨特的秋景，歡迎民眾一起來體驗一場精彩絕倫的風箏嘉年華。',
        participation: '',
        cityId: 510,
        address: '桃園市 大溪區中庄調整池景觀土丘',
        tel: '',
        org: '桃園市政府觀光旅遊局',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年延期辦理',
        noncycle: '',
        website: 'https://travel.tycg.gov.tw/',
        longitude: '24.9257463',
        latitude: '121.3181692',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '桃園市  大溪區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080495/d5fd5db7a2a672236a7e2bf9d409d00777298301.jpg',
      },
      {
        actId: 368,
        actName: '2021高雄馬拉松',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '高雄馬拉松（Kaohsiung Marathon）自99年舉辦迄今已辦理10屆，由高雄市政府團隊、學校師生、地方廟宇、路跑團體、在地優質企業與社團等相關單位協力而成的大會組織，提供沿線夾道歡呼加油及整體服務品質深獲跑者肯定，連年獲譽為「全臺灣最友善的城市馬拉松」，其魅力與賽事指標性已深獲全國及國際跑者認定為年度首選賽事之一。\r\n每年吸引將近2萬名國內跑者及數百名國外跑者報名參加，透過路跑賽事飽覽高雄城市著名景點、體驗高雄文化，並感受港都奔放熱情的濃濃人情味。此外，高雄馬拉松自開辦以來每年均於元宵節前後舉行，為形塑元宵節熱鬧氛圍，近年更設置馬拉松燈籠大道或舉辦燈籠創意造型獎項，吸引民眾共襄盛舉，並打造全球少見的燈籠馬拉松。\r\n※ 原定於1月30、31日舉辦2021高雄富邦馬拉松因疫情宣布延辦，經評估已改延至10月30、31日，詳情請參考活動官網。',
        participation: '',
        cityId: 1811,
        address: '高雄市 左營區世運大道100號',
        tel: '',
        org: '高雄市政府運動發展局',
        startTime: 'Oct 30, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://khm.com.tw/',
        longitude: '22.7030372',
        latitude: '120.2944946',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '高雄市  左營區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080434/fb9027972b0f8d62b4150a73099cc4f92d40ebb7.jpg',
      },
      {
        actId: 388,
        actName: '2021福隆國際沙雕藝術季',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '「2020~2021年福隆國際沙雕藝術季活動」主題將結合交通部觀光局「2020脊梁山脈旅遊年」及「2021自行車旅遊年」，以福隆黃金沙雕雕塑出台灣及世界「脊梁山脈及自行車旅遊意象」；藉由沙雕師駐校與巡迴深耕教學，國際及國內沙雕大賽之舉辦，為國內沙雕藝術界培養新血與提供發展舞台。',
        participation: '',
        cityId: 310,
        address: '新北市 貢寮區福隆街40號',
        tel: '',
        org: '交通部觀光局東北角暨宜蘭海岸國家風景區管理處',
        startTime: 'Sep 17, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://events.necoast-nsa.gov.tw/sandart21/',
        longitude: '25.0219984',
        latitude: '121.9431583',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  貢寮區(貢寮鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080454/0fa044531ab3f1de5cc4c32f145e68ceb9d6ca78.jpg',
      },
      {
        actId: 410,
        actName: '2021臺北時裝週',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '做為臺灣時尚產業最重要的溝通平臺，2021年臺北時裝週首度以一年兩季的發表頻率銜接國際時尚圈的節奏。三月登場的AW21將於松山文創園區舉行。最受矚目的「永續時尚開展秀」於3月11日晚上為臺北時裝週揭開序幕，包含13場臺灣設計師品牌秀精彩登場，為城市注入時尚創意動能。\r\n從去年初至今，全球產業大受疫情影響，打斷了長久以來國際間時裝週穩定而繁忙的節奏，甫結束的臺北時裝週 SS21 以全球少數的實體時裝週展演形式備受產業關注，帶動不少國際媒體討論聲量。在這個重生與創新的年代，臺北時裝週重新定義溝通核心，以前所未見的面貌登場，由「機能、永續、跨界、多元、人文」五大訴求出發。在生產面，串連臺灣領先全球的機能布料開發技術，帶動產業發展永續時尚的創新工法與創意思維；在設計面，融入臺灣實力堅強的各界藝術文化與時尚產業交流更多合作可能，激盪創作靈感，將風格融入日常，展現多元文化並存的豐富生活面貌。\r\n「2021臺北時裝週 AW21」加強整合時尚產業上、中、下游能量，打造一個結合表演藝術、美術視覺設計、原創音樂等相關產業跨界合作的優良環境，行銷臺灣設計師品牌並推展國際交流。期待在疫情衝擊的市場環境挑戰下，凝聚實力，放眼未來，發展屬於臺北時裝週的獨特美學風格。\r\n\r\n    臺北時裝週 AW21（秋冬季）：3/10-3/15\r\n    臺北時裝週 SS22（春夏季）：10/3-10/17\r\n',
        participation: '',
        cityId: 107,
        address: '臺北市 信義區松山文創園區四號倉庫',
        tel: '',
        org: '文化部、經濟部、教育部',
        startTime: 'Mar 10, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '時裝週AW21：3/10-3/15、時裝週SS22：10/3-10/17',
        noncycle: '',
        website: 'https://www.tpefw.com/',
        longitude: '25.0443585',
        latitude: '121.5600944',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  信義區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080482/b80fee9c3ca9d15c2bce5475a07e53eebfe2aec3.jpg',
      },
      {
        actId: 413,
        actName: '2021雲林國際偶戲節',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '雲林縣政府每年舉辦「雲林國際偶戲節」與民眾共襄盛舉，以藝術與國際接軌。現今布袋戲也躍升台灣「國家意象」之代表，素有布袋戲的故鄉之稱-雲林，自1999年開始籌劃舉辦『雲林國際偶戲節』，邀請國際偶戲工作者來台表演，豐富全國觀眾的文化藝術內涵與視野，讓傳統文化藝術進入民眾的生活中，也能讓本土與外國偶戲團體互相觀摩切磋演技，增進彼此經驗交流，永續發展與創新。\r\n為保存及推動布袋戲傳統文化，將這項傳統民俗透過國際文化之交流與刺激，與「金掌獎」活動辦理，讓掌中乾坤的藝術與時俱進，讓即使不懂、不看布袋戲的人，能親近進而喜歡上布袋戲詼諧逗趣，欣賞到布袋戲精萃之美，使布袋戲偶戲文化得以傳承。\r\n雲林國際偶戲節自1999年開辦至今(2021)年，將邁入第19屆，已是台灣「資深」的重要慶典，本年度以武林天下為策劃主題，提取雲林縣特有的金光戲，以武俠為題，且充滿各路英雄角色、金掌獎偶藝競技等元素，展現布袋戲多元的風貌。而不同角色間的碰撞交織，成就武林，也寫下故事，恰恰對應台灣社會由不同民族組成的風貌，期許透過看偶戲，也看見台灣多元社會價值。  --\u003e',
        participation: '',
        cityId: 1303,
        address: '雲林縣 虎尾鎮雲林布袋戲館',
        tel: '',
        org: '雲林縣政府',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '23.709297',
        latitude: '120.4335627',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '雲林縣  虎尾鎮',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080486/affcf73cebbb72c2e04e0a9e6a68e4aaf2903e83.jpg',
      },
      {
        actId: 399,
        actName: '2021生態賞鷗暨海上看馬祖',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '生態',
        description: '馬祖列島由36個大小島嶼組合而成，分布密集的島嶼、低人為破壞的環境及得天獨厚的地質景觀，形成馬祖獨一無二的海岸地形。早期為配合戰爭需要，開挖了為數甚多的坑道碉堡，從陸地上無法發現，唯有從海上方能看見奇偉壯麗的花崗石岩岸搭配鬼斧神工的砲堡碉堡，體會莫可名狀的感動。而在燕鷗繁殖季，保護區迎來上萬的燕鷗嬌客，其中大多是保育類，全世界僅存100隻的「神話之鳥\u0026ndash;黑嘴端鳳頭燕鷗」，最高數量達20幾隻，是非常珍貴的資源；搭配隨船解說員生動又富教育意義的解說，能帶給遊客難忘的生態巡遊經驗。',
        participation: '',
        cityId: 2501,
        address: '連江縣 南竿鄉福澳港',
        tel: '',
        org: '連江縣政府交通旅遊局',
        startTime: 'Jul 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: '',
        longitude: '26.159801',
        latitude: '119.943182',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '連江縣  南竿鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080471/d70b75433f35a870cfb5cc9984a40e87da433f8f.jpg',
      },
      {
        actId: 401,
        actName: '2021新北市兒童藝術節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '新北市的兒童擁有專屬的表演藝術節慶活動，開啟在地兒童表演藝術團隊的創意，並為在地兒童表演藝術團隊與國際搭建接軌平臺，自100年新北市兒童表演藝術節結合藝術教育推廣計畫，辦理至今已近十年，近年來將新北市市民廣場變身為童話城堡，首創「歡樂大遊行」：自府中商圈至市民廣場，參與人數年年創新高，去年已近破百萬人次參與。\r\n「新北市兒童藝術節」做為新北市政府最吸眾活動之一，特定為「兒童」舉辦之暑期大型活動，提供兒童一個具趣味性及教育性之接觸、認識藝術機會，以定點、帶狀、亮點方式呈現，辦理嘉年華會式兒童藝術節慶活動，以表演、遊戲、參與的型式，提供兒童多樣性、多元化的藝術展演內容，為擴大藝術扎根、縮短藝文資源城鄉差距及培養兒童參與藝文的習慣。為孩子們打造了充滿魔力的童話城堡，滿足孩子們無限的想像。\r\n新北市兒童藝術節往年為實體活動，因應疫情改為線上活動，免費提供大小朋友有趣的藝術體驗。今年主題為怪獸競技場，結合全國運項目及數位體驗，打造適合親子一起享樂的空間，有怪獸奇幻草原（表演節目及藝術裝置）、歡樂大遊行、10款好玩AR濾鏡、怪獸主題歌舞、還有煙火秀，宅家玩兒藝又做好防疫。\r\n※因受疫情影響，新北市兒童藝術節將全面改為線上辦理。',
        participation: '',
        cityId: 303,
        address: '新北市 板橋區新北市市民廣場',
        tel: '',
        org: '新北市政府',
        startTime: 'Aug 13, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.newtaipei-summer.tw/',
        longitude: '25.0122763',
        latitude: '121.4655369',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  板橋區(板橋市)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080473/df35efc4d3d7e3ecd6b7467232a1aec1ba3740aa.jpg',
      },
      {
        actId: 426,
        actName: '臺北溫泉季',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '北投長年為臺北觀光行銷亮點，更為溫泉文化領頭羊。「臺北溫泉季」自 2001 年推廣至今，已成為每年臺北市北投區秋季最大型國際活動。\r\n「臺北溫泉季」每年為吸引國內外觀光客造訪及參與，除展現北投溫泉鄉特有的人文風情及豐富資源外，也結合歷史文化、當地產業、古蹟建物、特殊地理環境、地方美食小吃等，讓溫泉季展現嘉年華般的熱鬧氛圍，並藉由各式活動的安排，如明華園溫泉季年度大戲、北投經典歌謠情、那卡西演唱、音樂表演、露天電影院等（依每年規劃主題而不同），讓國內外旅客可參與在地傳統活動，且能夠更深入地認識北投。\r\n此外，也藉由舉辦「臺北溫泉季」有效結合地方資源、促進當地產業發展及推廣觀光旅遊，營造自然環保、樂活悠閒及國際友善的旅遊環境，同時加強國內外媒體宣傳及擴大推廣效益，將北投優質的旅遊環境及豐富的觀光資源推向國際並成為臺灣最具代表性的國際溫泉勝地。',
        participation: '',
        cityId: 109,
        address: '臺北市 北投區捷運新北投站周邊',
        tel: '',
        org: '臺北市政府觀光傳播局、臺北市溫泉發展協會',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '25.136900',
        latitude: '121.502500',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  北投區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080499/a557cb86d4f135f62a4b0b9b7df0e641435ce43e.jpg',
      },
      {
        actId: 430,
        actName: '西拉雅趣飛車',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '西拉雅趣飛車是一場僅靠下坡自然動力而前進的速度運動，是一項極具「創意、娛樂、工藝」的趣味競賽。西拉雅趣飛車活動提供國人發揮工業技藝與創意靈感的平台，一方面讓具有機械設計才能的民眾一展長才，另一方面鼓勵民眾飛車整體造型上發揮搞怪、不計形象的創意，藉個人趣味創意充分炒熱觀賽氣氛，進而讓全世界，看見臺灣民眾活潑跳耀、天馬行空的創作潛能，傳遞歡慶氣氛、享受生命的歡樂形象。',
        participation: '',
        cityId: 1635,
        address: '臺南市 大內區二溪里唭子瓦60號',
        tel: '',
        org: '交通部觀光局西拉雅國家風景區管理處',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: 'https://www.siraya-nsa.gov.tw/zh-tw',
        longitude: '23.1371777',
        latitude: '120.4298584',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺南市  大內區(大內鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080504/420369a3a5596913c8f6bf9faf5fd6f9d5d00277.jpg',
      },
      {
        actId: 391,
        actName: '2021觀音觀鷹-觀音行腳樂活系列活動',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '生態',
        description: '因應疫情，今年度觀音觀鷹行腳樂活系列活動改為9至10月辦理，活動分為「悠遊觀鷹-生態導覽」、「觀音山步道安心遊-速寫導覽及健行導覽」、「尋！鷹雄好漢-尋寶拍照闖關」及「走讀觀音山生態體驗團」等，透過深度導覽帶領民眾認識觀音山生態之美。\r\n\u003c!--※因應本土疫情持續嚴峻，原定5/27（四）觀音觀鷹市集活動取消--\u003e',
        participation: '',
        cityId: 325,
        address: '新北市 五股區凌雲路三段130號',
        tel: '',
        org: '交通部觀光局北海岸及觀音山國家風景區管理處',
        startTime: 'Sep 1, 2021 12:00:00 AM',
        endTime: 'Oct 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.northguan-nsa.gov.tw/user/main.aspx',
        longitude: '25.129446',
        latitude: '121.418201',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  五股區(五股鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080459/df83331f173b6bdec66cab7375fbf6c653462de4.JPG',
      },
      {
        actId: 455,
        actName: '2021阿里山神木下婚禮',
        levelName: '國際級',
        grade1: '浪漫',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '阿里山管理處辦理神木下婚禮已邁入第15年，延續鄒族部落婚禮體驗、香林神木證婚兩大特色儀式，藉由部落婚禮充滿寓意的結婚祝福，將回憶留存心間，更是透過千年神木互許真愛諾言；同時，也結合轄區內的自然地景及人文資產，串連在地文化、特色店家、手作DIY體驗、美食饗宴，進而帶動周邊觀光發展，以期能為臺灣觀光產業盡一份心力。此外，更推出心意滿滿的結婚伴手禮，融入阿里山唯美地景意象「雲海、櫻花、紫藤、星空」，嚴選深具在地特色物產品牌，這些獨家限定的紀念禮品，都是為了陪伴新人踏入新婚生活，讓阿里山的美好能延續到日常。\r\n深度在地體驗，阿里山渡假婚旅\n\r\r\n隨著婚拍微旅行風氣盛行，阿里山管理處隆重打造「阿里山渡假婚旅」，規劃以台18線及西北廊道為主軸的兩種遊程，揉合在地自然人文資源與觀光產業，特別將茶文化融入體驗行程，加入蘊含祝福意味的「團茶」、「封茶」手作活動，象徵夫妻同心協力面對婚姻生活，為新人開啟充滿台灣特色的「婚拍、度假、小蜜月」全新選擇，進一步延續「浪漫阿里山」的品牌初衷。\r\n超有愛婚紗紀錄，取景阿里山獨門秘境\n\r\r\n「阿里山外景浪漫婚拍」亦是神木下婚禮的一大特點，新人只要自備喜歡的婚紗禮服，便能在新秘團隊的巧手下亮眼變身，走訪阿里山轄內絕美秘境，留下充滿台灣風情的唯美婚紗紀錄；若是擔心拍不過癮，阿里山管理處亦設計專屬「阿里山聯名婚拍方案」，攜手全台頂尖婚禮攝影團隊，深入多處阿里山獨到秘境，與新人一同解鎖更多美景回憶。',
        participation: '',
        cityId: 1504,
        address: '嘉義縣 阿里山鄉香林神木',
        tel: '',
        org: '交通部觀光局阿里山國家風景區管理處',
        startTime: 'Oct 31, 2021 12:00:00 AM',
        endTime: 'Nov 1, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.ali-nsa.net/zh-tw/event/calendardetail/1485',
        longitude: '23.5173506',
        latitude: '120.8081305',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '嘉義縣  阿里山鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080501/ebfb3ba56a39006beeaf7799952585aacaa8b666.jpg',
      },
      {
        actId: 434,
        actName: '2021六堆秋收祭系列活動',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '客家人利用「春祈、夏耘、秋收、冬藏」大自然時序變化，來調整一年作息的生活方式，是代代相傳的優美文化，而每年十月底十一月初正是豐收的時節，各地均會酬神以慶祝一年一度秋收祭的到來。\r\n為貼近民眾生活及帶動六堆客家地區觀光，今年秋收祭特以「親近自然」為主題發想，規劃一系列「謝天、迎秋神」、「千人開幕式」、「彩妝遊園活動」、「庄頭藝文」、「秋收主題體驗」、「食福宴暨聯歡晚會」等豐富活動，將客庄秋收的歡愉與故事，透過各項活動傳遞客家多元的文化面貌以表達我們對天地最深的敬意與情感。',
        participation: '',
        cityId: 2012,
        address: '屏東縣 內埔鄉信義路588號',
        tel: '',
        org: '客家委員會客家文化發展中心',
        startTime: 'Oct 22, 2021 12:00:00 AM',
        endTime: 'Nov 7, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '22.6584186',
        latitude: '120.5588158',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '屏東縣  內埔鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080508/e8393e9b12cfd8d2cea11ba2b483a805d739b6c2.jpg',
      },
      {
        actId: 420,
        actName: '2021日月潭花火音樂嘉年華',
        levelName: '國際級',
        grade1: '浪漫',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '日月潭花火音樂嘉年華系列活動自民國97年（西元2008年）起舉辦迄今，將觀光結合文化，以「藝文為主，花火為輔」作為活動主軸，邀請國內知名樂團，將大型藝術表演活動，搭配施放炫爛煙火，高品質的音樂花火聲光饗宴，在日月潭浪漫唯美之自然山光水景特色中演出，創造日月潭獨特之藝文氣息。近年來更逐漸導入自行車、馬拉松、紅茶產業文化、婚紗旅遊等多元主題，發展一系列高品質戶外展演及觀光活動，塑造多元嘉年華盛事意象，為日月潭嘉年華活動奠定深刻之「藝文表演」與「運動休閒」高優質旅遊印象，每年10-11月的日月潭花火音樂嘉年華活動已成為秋遊日月潭年度重大盛會。\r\n\r\n    10/30 NTSO臺灣青年交響樂團花火音樂會\n\r\r\n    暫定19:00開演，演出結束後施放煙火\r\n    10/30-10/31 紅茶文化季\n\r\r\n    10:00-16:00\r\n    11/13 日月潭Come!BikeDay自行車嘉年華\n\r\r\n    報到時間及地點視活動路線及內容而定，報名資訊後續公告\r\n',
        participation: '',
        cityId: 1210,
        address: '南投縣 魚池鄉水社碼頭',
        tel: '',
        org: '交通部觀光局日月潭國家風景區管理處',
        startTime: 'Oct 30, 2021 12:00:00 AM',
        endTime: 'Nov 13, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.sunmoonlake.gov.tw/zh-tw',
        longitude: '23.864501',
        latitude: '120.911917',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '南投縣  魚池鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080493/bf0fcc455f74336fe39c412b60d529a7712692cb.jpg',
      },
      {
        actId: 377,
        actName: '2021新北市萬金石馬拉松',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '新北市萬金石馬拉松自2015年起已連續三年獲得IAAF銅標籤認證，2018、2019年更升級為銀標籤認證，成為全臺唯一獲得銀標籤認證的馬拉松賽事，同時也是奧運資格賽之一。此認證主要是表彰世界各地優秀馬拉松賽事，並登錄世界馬拉松年度賽事行事曆，給予辦理賽事城市的肯定，藉此吸引更多世界各地跑友來臺參賽。\r\n2020年賽事為了提高品質，新北市全力朝著「金標籤」認證邁進，逐步提升賽事規格。此外，為了迎接世界各國跑友來臺，萬金石地區里民投入支援不遺餘力，充分展現臺灣人民的熱情。賽道路線同時呈現在地特色風光及海岸線之美，讓賽事參與者擁有更美好的感官體驗，藉此行銷新北城市形象，讓世界看見新北市，讓世界看見臺灣。\r\n※受新冠肺炎疫情影響，為保障選手及所有參加人員的健康與安全，2021新北市萬金石馬拉松延期至110年11月21日舉辦。',
        participation: '',
        cityId: 301,
        address: '新北市 萬里區群策翡翠灣溫泉飯店第二停車場',
        tel: '',
        org: '新北市政府、中華民國田徑協會',
        startTime: 'Nov 21, 2021 12:00:00 AM',
        endTime: 'Nov 21, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.wanjinshi-marathon.org/',
        longitude: '25.1898',
        latitude: '121.684059',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  萬里區(萬里鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080443/faa487c979ae2041ad8e0c2b6972b080b6b5fa9b.jpg',
      },
      {
        actId: 416,
        actName: '2021新北萬里蟹',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '美食',
        grade6: '',
        description: '本市每年訂於9月辦理萬里蟹產季起跑記者會，除宣告萬里蟹產季正式到來，並預告10月至12月即將舉辦的一系列萬里蟹季產地活動，如淡水肥蟹宴、富基品蟹宴、野柳假日活蟹市集、龜吼漁夫市集萬里蟹促銷活動等，以萬里蟹之名串連新北特色漁港，系列活動最高潮為10月於野柳漁港盛大舉行的萬里蟹主場活動，讓民眾來到產地品嚐鱻蟹宴，現場其他民眾還可以參加搭乘娛樂漁船體驗捕蟹人生、走訪野柳咾咕厝、瑪鋉居及保安宮等漁村風情導覽以及海洋獨木舟等漁業體驗活動，藉由系列活動讓民眾就近到漁港體驗休閒漁業活動，進而以行動支持在地漁業的永續發展。\r\n\r\n    野柳假日活蟹市集 2021/09/18~2021/11/28  每週六、日 (含中秋連假、雙十連假) 09:00 ~17:00\r\n    萬里蟹線上特展-萬里蟹小任務 2021/09/13~2021/10/11\r\n',
        participation: '',
        cityId: 301,
        address: '新北市 萬里區野柳漁港',
        tel: '',
        org: '新北市政府',
        startTime: 'Sep 13, 2021 12:00:00 AM',
        endTime: 'Nov 28, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://wanlicrab.tw/',
        longitude: '25.2058714',
        latitude: '121.6870639',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  萬里區(萬里鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080489/7e50b4aa2d1870832767b275ccbf7862e875bbeb.jpg',
      },
      {
        actId: 435,
        actName: '2021菊島澎湖跨海馬拉松',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '旅跑熱潮開始延燒吹動離島賽事崛起，也將成為馬拉松融入「運動觀光」及「旅跑概念」，醞釀而成為新賽點及新亮點。臺灣本島因可供舉辦馬拉松的場域有限，各縣市路跑賽事的路權取得不容易，許多賽事也多規劃為折返跑路線，唯獨澎湖國家風景區管理處所籌辦之菊島澎湖跨海馬拉松，是堪稱為外島首創的 A-B 點不折返、跳島、不繞圈的賽道，並取得國際賽道認證，讓跑友們更能全程以一步一腳印的方式，完整、深入體驗澎湖之美。\r\n※鑑於臺灣因應嚴重特殊傳染性肺炎(COVID-19)疫情所實施之防疫警戒仍未完全解除，主辦單位決定持續配合防疫，將原訂於（2021年11月7日）舉辦之-2021菊島澎湖跨海馬拉松，延期至2022年辦理（暫定於2022年11月6日舉辦）。',
        participation: '',
        cityId: 2102,
        address: '澎湖縣 西嶼鄉外垵村1鄰1之15號',
        tel: '',
        org: '交通部觀光局澎湖國家風景區管理處',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年延期辦理',
        noncycle: '',
        website: 'https://www.penghu-nsa.gov.tw/',
        longitude: '23.5656491',
        latitude: '119.4896972',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '澎湖縣  西嶼鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080509/bfd285d2803e452a6e0764d5a2d176042201d29d.jpg',
      },
      {
        actId: 436,
        actName: '金門坑道音樂節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '本處擁有許多珍貴的戰役資源，尤因戰役挖鑿的各式坑道，更是金門遊憩資源的重點。為發揮金門特色，本處籌劃辦理「金門坑道音樂節」活動，以鬼斧神工的翟山坑道作為天然音箱，讓演奏、演唱者的聲音更加純淨，祈以悠揚的音樂，讓世人體會翟山坑道獨一無二的歷史場景，並以音樂化身和平的天使，共創幸福的未來。',
        participation: '',
        cityId: 2404,
        address: '金門縣 金城鎮翟山坑道',
        tel: '',
        org: '金門國家公園管理處',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '24.390301',
        latitude: '118.3206168',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '金門縣  金城鎮',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080510/0a8ae43f471ca758fea30337c8d9f50d7fa33dc3.jpg',
      },
      {
        actId: 437,
        actName: '草嶺古道芒花季',
        levelName: '全國級',
        grade1: '浪漫',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '為讓遊客欣賞大片芒花壯闊盛開之景，感受草嶺古道那段跨越百年山海時光長廊的記憶，東北角暨宜蘭海岸國家風景區管理處自2002年起開始舉辦「草嶺古道芒花季活動」，迄至2020-2021年已推廣近20年，近年來已成為東北角地區觀光旅遊品牌活動，每年度總吸引約8萬人次遊客前往欣賞滿山芒花的迷人風采，今年度的芒花盛宴，亦將持續以輕鬆、詼諧的方式推廣，帶領大家一同踏上擁有兩百年歷史的古道，典藏古道秋芒美麗的記憶。',
        participation: '',
        cityId: 310,
        address: '新北市 貢寮區草嶺古道',
        tel: '',
        org: '交通部觀光局東北角暨宜蘭海岸國家風景區管理處',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: 'https://www.necoast-nsa.gov.tw/',
        longitude: '24.9900071',
        latitude: '121.9253726',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '新北市  貢寮區(貢寮鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080511/f1e3a4c28e7d7c26d8f6235c2d3b48fb6e91973e.jpg',
      },
      {
        actId: 438,
        actName: '屏東國際風箏節',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '配合每年屏東國際風箏節，屏東縣政府於活動前陸續舉辦一系列相關活動，除了到社區關懷據點及學校敎作風箏外，更有風箏設計種子教師研習營及我愛河川書法比賽等系列活動，每年的屏東國際風箏節，縣府特別邀請了國內外專業風箏團隊進行鬥箏PK賽等表演，展現其所創作的藝術風箏作品與精湛的風箏放飛技巧，各具特色的造型風箏、硬板風箏及特技風箏都會在活動當日同時綻放在天空。\r\n活動期間除了滿天的造型風箏及地面上的地景風箏外，還安排有特色產業市集、捐發票換風箏、親子彩繪風箏DIY、泡泡滿天飛、樂樂棒球賽、滑步車比賽及自行車遊河濱\u0026hellip;\u0026hellip;等相關活動，在高屏溪河濱公園裡，透過不同的活動，讓民眾除了可以欣賞風箏表演，更可以透過各系列活動增進家庭親子關係並鼓勵社區民眾多參與正當休閒活動。',
        participation: '',
        cityId: 2001,
        address: '屏東縣 屏東市高屏溪河濱公園',
        tel: '',
        org: '屏東縣政府',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '22.6475967',
        latitude: '120.4421037',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '屏東縣  屏東市',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080512/329df7244c9781d88077214a15886ad13f9fabf2.jpg',
      },
      {
        actId: 439,
        actName: '2021臺灣米倉‧田中馬拉松',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '台灣最具人情味、台灣農村特色的馬拉松-台灣米倉田中馬拉松，全鎮出動六千位鄉親，展現田中的友善與熱情一路幫跑者加油，田中鄉親志工用滿滿珍惜土地的幸福感，營造友善熱情賽道，使「台灣米倉田中馬拉松Taiwan\u0027s Rice Heaven－Tianzhong Marathon」打響國內外知名度，廣受國內外跑者民眾喜愛，無不為了感受台灣在地風情與熱情好客的風情。\r\n2012年在地加油團的熱情替田中馬打出熱情制霸名聲，報名人數逐年增加，2016年因報名人數眾多開始改以報名抽籤，近年跑者人數皆突破16,000人，並連續超過三年皆評價為臺灣經典賽事前三名，為臺灣抽籤難度最高賽事，成為國內外跑者來台指定參與賽事，外媒號稱台版「東京馬」2018年超過22個國籍1,000位海外選手參賽。\r\n※因為對於2021年下半年的種種不確定性，也考量到參賽選手及工作夥伴的安全健康，經審慎評估後，2021田中馬將取消實體賽事，改以全新的「2021台灣米倉田中馬拉松線上跑」與大家在線上相聚。',
        participation: '',
        cityId: 1117,
        address: '彰化縣 田中鎮中州路一段416號',
        tel: '',
        org: '彰化縣政府、舒康運動協會',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: '',
        longitude: '23.8573781',
        latitude: '120.5816341',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '彰化縣  田中鎮',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080513/7629632f04e7c08905891c42aec476828b2d8c5c.jpg',
      },
      {
        actId: 441,
        actName: '鐵路便當節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '美食',
        grade6: '',
        description: '鐵路便當節為交通部臺灣鐵路管理局以便當會友，擴大邀約國際業者參與，共同展現鐵道文化之美，以軟性的行銷策略與活動規劃，使國內民眾進一步了解臺灣鐵路管理局的多元服務，對外溝通則以「臺灣」為品牌，透過雙邊互動，由單點的在地美食推廣，拓展至全方位的國際觀光交流。\r\n為提倡社會設計與美學生活的結合，將邀請民眾一同來詮釋鐵路美學，希望募集從不同地區、視角與觀點之臺鐵之美，無論從彩繪列車、鐵道風景都是切入的角度， 廣邀民眾參與，分享每個人心目中不同的鐵道故事，不僅於活動現場設置「鐵路便當專屬繪畫牆」之外，首獎將獲得鐵路便當節限量紀念品與獎金1萬元整，還有機會將作品印刷在臺鐵便當外盒包裝上喔！快提起畫筆，讓心中那個醞釀許久的故事有機會被看見！【移動社計師】臺鐵美學繪畫比賽等您一起來分享！\r\n--\u003e\r\n除了鐵道美食及商品外，主題活動還有：「成就經典戲院」，邀請到劉克襄、陳朝強、郭佩怜、凌宗魁等多位各領域專家，一同從鐵道出發，賞析與分享屬於他們與鐵道的動人故事。「親子館」則以便當研習所，主題規劃DIY體驗活動，歡迎家長帶著小朋友一同了解臺鐵美食文化。「鐵道Ｘ跨界論壇」，在展期周末及週日將舉辦四場論壇，分別以美食、文創、旅遊、與設計四大主題，邀請到多位重量級講者齊聚一堂，與民眾一同探討分享屬於臺鐵的經典與未來。\r\n誠摯邀請大家呼朋引伴，到臺北車站大廳參加「2020第6屆鐵路便當節」，感受將透過更多樣化的臺灣鐵道主題活動，集合文化創意與品牌設計，串聯出全臺鐵道一波體驗經典鐵道浪潮！',
        participation: '',
        cityId: 101,
        address: '臺北市 中正區北平西路3號',
        tel: '',
        org: '交通部臺灣鐵路管理局',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '25.0478142',
        latitude: '121.5169488',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  中正區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080515/dbabfeb153dca58ef1f3023b42ec7523b0573712.jpg',
      },
      {
        actId: 442,
        actName: '2021鯤鯓王平安鹽祭',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '雲嘉南濱海獨特的鹽田景觀，所孕育出的鹽產業文化與鹽村生活寫照風光，留下豐富且令人追憶的文化資產。\r\n活動以臺灣王爺信仰總廟「南鯤鯓代天府」（國定古蹟），以及鹽民的原鄉「北門」，作為活動出發點，除了帶領大家體驗臺灣西南濱海地帶獨有之鹽業歷史、鹽田風光及宗教文化外，也藉此行銷其他資源特色，如：濕地生態、冬候鳥等，另透過活動結合濱海地區嚴選美食伴手禮資源，共同推廣在地的旅遊、美食與特產，期提升相關產業之產值，並藉由此活動打響雲嘉南濱海國家風景區之名聲，帶領遊客探訪雲嘉南美麗的風光。',
        participation: '',
        cityId: 1625,
        address: '臺南市 北門區鯤江里976號',
        tel: '',
        org: '雲嘉南濱海國家風景區管理處',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: 'https://swcoast-nsa.travel/',
        longitude: '23.2860869',
        latitude: '120.1431350',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺南市  北門區(北門鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080517/ef3af0a7f287bec68b97a65f04f59942d33a6a54.jpg',
      },
      {
        actId: 376,
        actName: '2021南島族群婚禮',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '本處轄區位於高屏山麓，在轄管的6個鄉區中，有5個鄉區為原住民地區，族群包含魯凱、排灣、布農及拉阿魯哇族等，呈現多元的原住民文化特色。為推廣本轄特有的原住民文化，帶動部落觀光發展，希望藉由「南島族群婚禮活動」之辦理，以原住民傳統婚禮為主軸，運用觀光行銷手法，將婚禮活動包裝為具有文化特色的觀光活動，活動期間並結合轄區特色民宿、工藝、美食、伴手禮等資源及遊程安排，期盼參與活動的新人、家屬與遊客深度體驗原住民文化及婚禮特色，並帶動觀光發展及地方產業效益。\r\n「南島族群婚禮」系列活動將於每年3月份舉辦，規劃以排灣族傳統婚禮為活動主軸，藉以行銷推廣茂林國家風景區旅遊線，讓更多遊客參與活動。本系列活動將運用觀光行銷手法，結合轄區工藝、美食與伴手禮等資源及套裝遊程安排，使參與活動的新人、家屬與遊客能深度體驗原住民文化及婚禮特色，藉以帶動觀光發展及地方產業，並達成行銷轄內觀光遊憩景點和推廣原鄉部落景致之目標。\r\n※ 為因應新冠肺炎疫情，2021南島族群婚禮活動決議延期至11月辦理。\r\n\r\n    開幕活動：11/12（星期五）\r\n    新人之夜：11/19（星期五）\r\n    主婚禮活動：11/20（星期六）\r\n    部落市集：11月每個星期六、日，共8日\n\r\r\n    11/6、11/7、11/13、11/14、11/20、11/21、11/27、11/28\r\n',
        participation: '',
        cityId: 2003,
        address: '屏東縣 霧台鄉霧台部落文化廣場',
        tel: '',
        org: '交通部觀光局茂林國家風景區管理處',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://www.facebook.com/austronesian.wedding',
        longitude: '22.744066',
        latitude: '120.730976',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '屏東縣  霧台鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080442/76d4dc3d94b8282d1c1276a51dc9b577419ae09d.jpg',
      },
      {
        actId: 404,
        actName: '臺灣滷肉飯節',
        levelName: '全國級',
        grade1: '',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '美食',
        grade6: '',
        description: '臺灣美食是吸引觀光客來臺的主因，其中最具代表的食物當然是用臺灣在地的米、豬肉及醬油烹煮而成的「滷肉飯」，美國CNN也報導滷肉飯是來臺必吃美食第1名，因此，經濟部規劃辦理「經濟部臺灣滷肉飯節」活動，將「滷肉飯」打造為「臺灣國飯」，行銷給國內消費者及海外旅客，讓這個臺灣美食走向全世界，讓大家用滷肉飯看見臺灣。',
        participation: '',
        cityId: 1004,
        address: '臺中市 西區市民廣場',
        tel: '',
        org: '經濟部',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '24.15',
        latitude: '120.6635',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺中市  西區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080476/9e3edb82926ba55c45822f9f1d52067915e74e7f.jpg',
      },
      {
        actId: 408,
        actName: '2021龍岡米干節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '美食',
        grade6: '',
        description: '第二次國共內戰，雲南有一支不願投降共產黨的部隊流亡進入了緬甸異鄉，成為「異域孤軍」。1953～1954年異域孤軍撤回台灣，移居在桃園龍岡地區，因此處位於中壢-平鎮-八德的交界處，加上獨特滇緬文化，因此有「魅力金三角」之稱。桃園市政府自2011年起辦理米干節活動，推廣在地獨特滇緬文化及美食；2014年結合潑水節，以「水花火舞」雙慶聯歡之主題辦理，並挑戰金氏世界紀錄，締造世界之最3000碗的「米干長龍」；2015年以雲南傳統長街宴做為開幕亮點，結合在地米干店家推出特色料理聯合宣傳米干美食；2016年邀請國際貴賓參加火把晚會活動，將龍岡米干節推向國際；2017年擴大長街宴規模，開放民眾報名參加，2018年首度移師龍岡大操場舉辦，並加入雲南特有「跳菜」元素，2019年活首度辦理「目腦縱歌狂歡節」，更將活動延長為三周，同時更推出「七彩米干」、「長街宴」、「雲南普洱茶席」三大在地美食饗宴。\r\n※2021年「龍岡米干節」改以「龍岡魅力小旅行」呈現。\r\n為讓更多民眾深度體驗桃園龍岡之美，2021年桃園市政府觀光旅遊局與雄獅旅遊、可樂旅遊攜手自即日起到11月30日推出11條龍岡魅力小旅行路線，報名參加就送價值超過新台幣200元的美食文化體驗券，邀您一同造訪充滿濃濃異域風情的桃園龍岡！詳細活動辦法請參考桃園市政府。',
        participation: '',
        cityId: 501,
        address: '桃園市 中壢區龍岡大操場',
        tel: '',
        org: '桃園市政府觀光旅遊局',
        startTime: 'Sep 23, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年以「龍岡魅力小旅行」呈現',
        noncycle: '',
        website: '',
        longitude: '24.9295618',
        latitude: '121.2380887',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '桃園市  中壢區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080480/a0ab9a671d3da50859cc6c99fe057012eaf9b0bc.jpg',
      },
      {
        actId: 431,
        actName: '二水國際跑水節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '「二水跑水節」為全國特有的水圳節慶活動，1719年彰化縣因八堡圳開鑿完成，得以引濁水溪水潤養彰化平原，而使彰化縣開發成為農業大縣。為敬天謝地及感懷先人德澤，在這個深具歷史文化意涵的「八堡圳」舉辦跑引水活動，傳揚歷經十年開鑿八堡圳的辛勞，展現不輕易放棄的毅力，是「台灣精神」最有力的表現，其意義也在推崇「飲水思源」、「食果子拜樹頭」的美德。\r\n每年11月進入秋收冬藏之際，在八堡圳舉辦一系列祈福活動，結合二水文化、跑水體驗、山海線農特產品、國際城鄉交流等，注入更多文化觀光元素，並行銷二水鄉的觀光特色，活化農村經濟，結合運動休閒及農特產，為活動注入文化創意活水，更讓二水國際跑水節提昇國際能見度。',
        participation: '',
        cityId: 1126,
        address: '彰化縣 二水鄉林先生廟',
        tel: '',
        org: '彰化縣文化局',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '23.7992032',
        latitude: '120.6449042',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '彰化縣  二水鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080505/e26539df73f4d5a047eb813baa619e5aaebb7d1a.jpg',
      },
      {
        actId: 432,
        actName: '桃園花彩節',
        levelName: '全國級',
        grade1: '浪漫',
        grade2: '',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '桃園花彩節運用農地休耕期間，規劃大面積花海、周邊農事體驗等活動，已經成為許多人每年必訪的行程之一！\r\n近年更加入「地方創生」概念，輔導在地休閒農業區轉型、曝光，促進城鄉發展、觀光經濟再生，打造桃園美麗的花卉產業，結合大面積花海、農事體驗、鄉村小旅行、假日音樂饗宴等活動，給您一個繽紛豐富的悠閒時光。\r\n自2015年舉辦以來，桃園花彩節已邁入第六屆，歷經幾年的成長，孕育出許多百萬人氣的桃園特色花卉活動，例：桃園彩色海芋季（每年約3-4月）、桃園仙草花節（每年約11-12月），皆是由此成熟獨立發展的特色活動，歡迎大家一起參觀桃園美麗的花卉產業。',
        participation: '',
        cityId: 504,
        address: '桃園市 楊梅區秀才休閒農業區',
        tel: '',
        org: '桃園市政府農業局',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: 'https://travel.tycg.gov.tw/',
        longitude: '24.8978031',
        latitude: '121.1158468',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '桃園市  楊梅區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080506/7501eb021b8769a7a75095a53d8ed7eca314170c.jpg',
      },
      {
        actId: 450,
        actName: '臺灣國際衝浪公開賽暨東浪嘉年華',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '臺灣四面環海，擁有豐沛的海洋資源，其中臺東擁有全國最長176公里海岸線，在東北季風吹拂下，助長東河、金樽一帶浪勢，尤其金樽得天獨厚地形、風向與水質，成為全臺灣難得衝浪首選之地。\r\n灣唯一列入ASC和WSL的國際衝浪場地，自2011年舉辦以來，以國際標準最高規格及裁判群為目標，屢次吸引超過10個國家選手前來參與。\r\n「東浪」主要是透過衝浪運動，行銷水域運動，並且推廣台灣秋冬季節的另類玩法。藉由建立衝浪意象主題，辦理遊客深度活動體驗，豐富肢體體驗、腦力知識、互動為設計主軸，深化旅客水域衝浪體驗，遊客可以到活動現場親自欣賞國際選手的表演及國內好手競賽英姿，並到台東的衝浪店體驗衝浪相關周邊活動，如直立單槳(SUP)、獨木舟\u0026hellip;等非動力水域體驗活動，將臺東秋冬衝浪意象深植人心。透過衝浪賽事的行銷宣傳，讓國內外更有機會認識臺灣東海岸另一種風情，將臺東打造成為更富有熱情活力的國際衝浪聖地。',
        participation: '',
        cityId: 2210,
        address: '臺東縣 東河鄉金樽遊憩區',
        tel: '',
        org: '臺東縣政府、世界衝浪聯盟',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: 'https://www.taiwanopenofsurfing.org/tw/',
        longitude: '22.9451684',
        latitude: '121.2799066',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺東縣  東河鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080550/56ed14d63eacccc1de974a2b2b66127990bf0967.jpg',
      },
      {
        actId: 428,
        actName: '2021臺中國際舞蹈嘉年華',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '「臺中國際舞蹈嘉年華」藉由舞蹈表演之推廣，結合節慶活動，建立運動觀光與藝術文化交流平臺，促進臺灣本土文化藝術人士與海外各國多元藝術表演團體交流合作，把臺中城市公園化為戶外舞台，創造話題亮點並打造獨特觀光特色意象，凸顯舞蹈嘉年華成為臺中的觀光盛會品牌活動。',
        participation: '',
        cityId: 1001,
        address: '臺中市 中區臺中舊車站前廣場',
        tel: '',
        org: '臺中市政府觀光旅遊局',
        startTime: 'Oct 1, 2021 12:00:00 AM',
        endTime: 'Nov 30, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: 'https://travel.taichung.gov.tw/',
        longitude: '24.1372593',
        latitude: '120.6866659',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺中市  中區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080502/e96c501223ce39763800bd4713eadf35b5a01d23.jpg',
      },
      {
        actId: 371,
        actName: '2021臺北燈節',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '俗稱「小過年」的元宵節是源遠流長的傳統民俗節慶，臺北市政府自民國86年（西元1997年）辦理「臺北燈節」以來，歷經逾20年的蘊育及特色養成，成為民眾春節期間不可或缺的參觀去處，不僅將新年的歡慶氣氛導入城市行銷，更將傳承民俗元宵節慶文化規模足以媲美外國有名的盛大慶典，其成功之展演也成為各縣市競相仿效的目標，近年更利用互動科技與藝術表演，增添燈節魅力，提供賞燈民眾更多城市參與及創新體驗。\r\n※ 受疫情影響，2021臺北燈節延至耶誕節期間12月17日至26日辦理。',
        participation: '',
        cityId: 106,
        address: '臺北市 萬華區西園路',
        tel: '',
        org: '臺北市政府觀光傳播局',
        startTime: 'Dec 17, 2021 12:00:00 AM',
        endTime: 'Dec 26, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://2021lanternfestival.taipei/tc/index.htm',
        longitude: '25.034622',
        latitude: '121.498910',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  萬華區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080437/8b9b89f618affec5d74e1f4b0f653267566b54d3.jpg',
      },
      {
        actId: 357,
        actName: '2021阿里山四季茶旅活動',
        levelName: '全國級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '阿里山四季茶旅活動係藉由培訓在地茶旅達人、茶旅體驗環境氛圍營造及行銷推廣活動，推廣阿里山好茶及多元品茗情境；四季茶會活動以二十四節氣為主題，結合在地茶旅達人司茶，伴著阿里山自然地景風貌（如：櫻花、螢火蟲、瀑布、竹林、森林、黃頭鷺、紫藤、雲瀑等），山林芬多精，品茗阿里山優質茶湯滋味；本計畫並將旅遊動線串連到產地製茶體驗、旅宿及品茗，開發多元茶品、茶輕食、茶文創商品，並搭配本處阿里山日產業展及國際旅展等聯合行銷茶旅遊程，提供國人與國際人士預約體驗深度茶之旅，形塑專屬阿里山茶文化體驗觀光品牌，促進阿里山茶文化、生態、產業等在地創生及深耕，活絡阿里山在地觀光產業，創造阿里山茶旅觀光產業整體效益與產值。\r\n\r\n    春季線上茶旅 2021.03.13 - 2021.03.19\r\n    夏季茶會 2021.07.17 ※暫停辦理\r\n    秋季線上茶會 2021.09.11\r\n    冬季茶會 2021.12.11\r\n',
        participation: '',
        cityId: 1501,
        address: '嘉義縣 番路鄉阿里山國家風景區',
        tel: '',
        org: '交通部觀光局阿里山國家風景區管理處',
        startTime: 'Jan 1, 2021 12:00:00 AM',
        endTime: 'Dec 31, 2021 12:00:00 AM',
        cycle: '春季3/13-3/19、夏季活動停辦、秋季9/11、冬季12/11',
        noncycle: '',
        website: 'https://www.ali-nsa.net/zh-tw',
        longitude: '23.5112942',
        latitude: '120.8036725',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '嘉義縣  番路鄉',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080423/023678b15b20125dfe7d49e08eea46d4cdfef21e.jpg',
      },
      {
        actId: 389,
        actName: '2021臺灣自行車節',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '國片「練習曲」中一句經典對白：「有些事現在不做，一輩子都不會做了。」這句話帶動了全臺單車環島風潮，騎著自行車環繞臺灣本島之旅，也被許多人列為此生必做的事之一！自2010年以來，交通部觀光局積極舉辦「臺灣自行車節」系列活動，熱情邀請臺灣全民一同創造「騎」跡，將交通建設的創新成果，轉換成觀光旅遊的新資源，企圖把臺灣打造為國際級自行車休閒旅遊天堂。臺灣的公路系統完善，再加上地形優勢，騎著自行車時還可邊欣賞沿路壯闊美景，在臺灣單車環島是最方便又享受的旅遊行程！「臺灣自行車節」系列活動就是以自行車旅遊活動，結合了各縣市的觀光與交通資源力量，呈現出多元與在地的文化旅遊特色。在好山好水的陪伴下，吸引全世界自行車愛好者都能來朝聖，提供國內外遊客們多樣豐富休憩旅遊體驗，讓騎鐵馬不再是單純的運動，而是更豐富的身心靈上完美體驗。\r\n澎湖自行車跳島嘉年華\r\n\r\n    領騎服務 3/1-6/30\r\n    數位集章 7/1-10/31 ※停辦\r\n    澎湖跳島101k線上自行車活動 9/1-10/31\n\r\r\n    ※因應新冠肺炎疫情尚未完全解除危機，原訂9月26日辦理「澎湖跳島101K自行車」自行車活動，將改變活動型態為「線上自行車自我挑戰活動」。\r\n\r\n臺灣自行車登山王挑戰\r\n\r\n    扶輪盃陽明山自行車登山王挑戰 3/6(六)\r\n    臺灣KOM登山王之路-春季 3/19(五)\r\n    臺灣KOM登山王之路-夏季 6/28(一) ※延期至9/6(一)\r\n    臺灣自行車登山王挑戰 10/29(五)\r\n\r\nLight up Taiwan極點慢旅\r\n\r\n    極西點國聖港燈塔暨雲嘉南濱海經典小鎮自行車慢遊系列活動 4/1-10/31\r\n    極北點騎遊系列活動 (日期尚未確定)\r\n\r\n馬祖之壁自行車挑戰遊 5/28(五)-5/31(一) ※停辦\r\nEast of Taiwan 花東海灣盃自行車挑戰 9/11(六)-9/12(日) ※停辦\r\nBike Taiwan 臺中自行車嘉年華 (日期尚未確定)\r\n日月潭Come!Bikeday自行車嘉年華 11/13(六)\r\n騎遇福爾摩沙 Formosa 900 11/6-11/14',
        participation: '',
        cityId: 2101,
        address: '澎湖縣 馬公市澎湖國家風景區管理處',
        tel: '',
        org: '交通部觀光局',
        startTime: 'Feb 1, 2021 12:00:00 AM',
        endTime: 'Dec 31, 2021 12:00:00 AM',
        cycle: '',
        noncycle: '',
        website: 'https://taiwanbike.taiwan.net.tw/',
        longitude: '23.5565649',
        latitude: '119.6064662',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '澎湖縣  馬公市',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080456/3d7e809b129c9fb3ea9e70296d865fb35485183a.jpg',
      },
      {
        actId: 445,
        actName: '嘉義市國際管樂節',
        levelName: '國際級',
        grade1: '',
        grade2: '文化',
        grade3: '',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '嘉義市國際管樂節從1993年開始5校樂團表演的「音樂節」，逐漸擴大參與廣度，成為全民參與的「城市節慶活動」。於今年本活動已邁入第29屆，不僅為嘉義市最具特色的文化節慶、亦是台灣具代表性的文化活動，被交通部觀光局列為台灣國際級觀光節慶活動之一。歷年來結合重大的音樂盛會，例如，2000年辦理亞太管樂節、2011世界管樂年會、2013亞洲雙簧年會、2016亞洲薩克斯風大會，已獲得了國內外音樂界的美名與口碑，更以「聲音的城市」、「管樂城」成為全台特色。',
        participation: '',
        cityId: 14,
        address: '嘉義市 西區中央噴水池',
        tel: '',
        org: '嘉義市政府',
        startTime: 'Dec 1, 2021 12:00:00 AM',
        endTime: 'Dec 31, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: '',
        longitude: '23.4799152',
        latitude: '120.4496322',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '嘉義市',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080545/d34877dc8a262610aea6f1c185311a819d30a974.jpg',
      },
      {
        actId: 451,
        actName: '2021新社花海節',
        levelName: '國際級',
        grade1: '浪漫',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '「新社花海」活動以「幸福花海、慢活山城、悠遊臺三線」為主軸，促進花海及山城自然農村特色與休閒農業區活動，營造「慢城」、「慢活」與「漫遊」的臺三線，進行點、線、面之推動，打造屬於山城地區之農村休閒、體驗及療癒之新興產業。活動以農委會種苗改良場第二農場40公頃土地為基地，營造秋季花海饗宴。常年則以國家級推動方案之「浪漫臺三線-農情客家庄」環境整備目標，打造中部山城地區環境優美之入口意象。',
        participation: '',
        cityId: 1018,
        address: '臺中市 新社區協成里協興街30號',
        tel: '',
        org: '臺中市政府、行政院農業委會種苗改良繁殖場',
        startTime: 'Nov 1, 2021 12:00:00 AM',
        endTime: 'Dec 31, 2021 12:00:00 AM',
        cycle: '2021年暫停辦理',
        noncycle: '',
        website: '',
        longitude: '24.2032599',
        latitude: '120.8059929',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺中市  新社區(新社鄉)',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080551/abfd8ed838981f6c3ca4254b792be5a0368c91cc.jpg',
      },
      {
        actId: 456,
        actName: '臺北馬拉松',
        levelName: '國際級',
        grade1: '',
        grade2: '',
        grade3: '樂活',
        grade4: '',
        grade5: '',
        grade6: '',
        description: '臺北馬拉松自1986年首次舉辦，活動訂於每年12月第3週週日（亦配合重大活動彈性調整）舉行，是台灣規模最大國際城市馬拉松賽事，自舉辦以來經過多年的努力，參賽選手水平逐漸提升，賽事也將朝向更加專業的菁英化領域邁進，並長期積極與國際接軌，提升賽事品質。\r\n為行銷臺北城市風貌，路線納入承恩門（北門）、麗正門（南門）、重熙門（小南門）和景福門（東門）等歷史韻味濃厚的古城門，並行經101大樓、仁愛路林蔭大道、臺北美術館及河濱公園等知名景點，充分呈現臺北市古今融合的城市風貌。',
        participation: '',
        cityId: 107,
        address: '臺北市 信義區市府路1號',
        tel: '',
        org: '臺北市政府、中華民國田徑協會、中華民國路跑協會',
        startTime: 'Dec 1, 2021 12:00:00 AM',
        endTime: 'Dec 31, 2021 12:00:00 AM',
        cycle: '2021年時間未定',
        noncycle: '',
        website: 'http://www.taipeicitymarathon.com/',
        longitude: '25.0379213',
        latitude: '121.5631307',
        class1: '01',
        class2: '02',
        map: null,
        travellinginfo: '',
        parkinginfo: '',
        charge: '',
        remarks: '',
        cityName: '臺北市  信義區',
        imageUrl: '/e_new_upload/task/a66dc343-cd8b-4ee0-a265-8d7fff520c3b/C2_315080000H_080543/637b4d2b91dd71faad4d683deb83830559b3b654.jpg',
      },
    ],
  }),
};
</script>

<style scoped>

</style>
