<template>
  <v-container>
    <h1>{{title}}</h1>
    <v-row>
      <v-col sm="8">
        <v-img
          :src="require('../assets/topic_img.png')"
        ></v-img>
      </v-col>
      <v-col sm="4">
        <div class="align-center text-left note">
          <h2>{{note}}</h2>
        </div>
      </v-col>
      <v-col sm="4"
             v-for="item in issue"
             :key="item.UID"
      >
        <Topic :topic="item"></Topic>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
import Topic from './Topic';

export default {
  name: 'TopicPage',
  components: { Topic },
  data() {
    return {
      title: '期間限定！報名從速，解封後不復見',
      note: '短短幾個月，我們的生活模式已被改變，\r\n學習、獲得新知，不一定需要面對面。\r\n開學啦！同學們，線上見！',
      issue:
      [
        {
          version: '1.4',
          UID: '6139d19eaaa3cf0fc41b991f',
          title: '達人講座x蘇瀅無所畏敢輸才會贏',
          category: '7',
          showInfo: [
            {
              time: '2021/09/28 19:00:00',
              location: '臺中市線上zoom平台',
              locationName: '線上zoom平台',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/28 20:00:00',
            },
          ],
          showUnit: '歌倫比亞美語顧問',
          discountInfo: '免費',
          descriptionFilterHtml: '在你的小小心中也有個大大的夢想，但是卻覺得很遙遠嗎？\r\n或是你正在前往夢想目標的過程中，快要被現實打敗了？\r\n來吧~ 蘇瀅有些話想要跟你分享！\r\n\r\n在成為網紅KOL之前的蘇瀅，\r\n曾經是個在夢想與現實之間掙扎的舞台劇演員。\r\n除了將過去打拼的歷程寫進新書「蘇瀅無所畏 敢輸才會贏」以外，\r\n也誠摯地邀請您一同來和蘇瀅線上面對面聊聊如何擁有面對失敗的勇氣。',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D9/E171/F926/54220f2d-f0f3-47f3-8ceb-a18359f2ecff.jpg',
          masterUnit: [
            '歌倫比亞美語顧問',
          ],
          subUnit: [
            'https://www.facebook.com/%E8%98%87%E7%80%85-Suri-771188916397653',
          ],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://www.clue.com.tw/webinars/LandingPage/Get/NmLH6',
          sourceWebPromote: 'https://www.clue.com.tw/webinars/LandingPage/Get/NmLH6',
          comment: '',
          editModifyDate: '',
          sourceWebName: '王怡蘋',
          startDate: '2021/09/28',
          endDate: '2021/09/28',
          hitRate: 13,
        },
        {
          version: '1.4',
          UID: '60d5e686aaa33e89fe9fbce2',
          title: '太平洋海盜#2：臨時自治區',
          category: '6',
          showInfo: [
            {
              time: '2021/06/20 00:00:00',
              location: '臺北市線上活動',
              locationName: '線上活動',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/30 00:00:00',
            },
          ],
          showUnit: '書寫公廠Writing FACTory（TW）ｘRRD（MX）',
          discountInfo: '',
          descriptionFilterHtml: '是翻玩？是致敬？是抄襲？還是所有權本來就有問題？！\r\n不出門就能參觀的🌊船上展覽🌊\r\n與你深入探究 #所有權 概念！\r\n\r\n太平洋海盜#2：臨時自治區｜Pirata Pacífico#2: TAZ\r\n2021.6.20-2021.9.30\r\n\r\n「太平洋海盜」是由台灣及墨西哥兩個藝術家團隊從2018年末開啟的計畫，\r\n討論總是被合法、非法一分為二的所有權及盜版問題。\r\n\r\n因為沒完沒了的殖民歷史，以及身旁住著巨型鄰國，\r\n對兩國而言，\r\n什麼才是「我的」成為不可說不可說的難題：\r\n🏴‍☠️ 在沒有新鮮事的太陽下，什麼叫「我的」作品？\r\n🏴‍☠️ 在各自經歷超過300年的殖民之後，什麼叫「我的」文化？\r\n🏴‍☠️ 在人與人的連結中，什麼叫「我的」情人？\r\n🏴‍☠️ 在人體工學設計都比你了解你的科技物件圍繞下，什麼叫「我的」身體行動？\r\n\r\n2021年，「太平洋海盜#2：臨時自治區（TAZ）」透過研究型線上駐村的方式，\r\n邀請三種領域、\r\n台墨共六位藝術家，\r\n從書寫、表演及聲響三個面相，\r\n超展開對於「盜版」的理解，\r\n不要錯過接下來一系列線上線下的工作坊及分享，\r\n按讚追蹤粉專 \r\n並到我們在Gather Town的海盜船上吹風聽浪！\r\n\r\n🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊🌊\r\n\r\n【主辦單位】\r\n關渡美術館\r\n\r\n【計劃發起】\r\n書寫公廠（台灣）\r\nRRD（墨西哥）\r\n\r\n【參與藝術家】\r\n楊政（台灣）\r\n康塞普西翁・赫爾塔（墨西哥）\r\n廖芸婕（台灣）\r\n珊德拉・桑切斯（墨西哥）\r\n林亭君（台灣）\r\n尤齊爾・克魯茲（墨西哥）\r\n\r\n【本計劃獲文化部辦理臺灣與拉丁美洲文化交流合作補助】\r\n\r\n',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D25/E222/F981/a22bf395-6369-43cd-b133-868930601c85.gif',
          masterUnit: [
            '關渡美術館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: '',
          sourceWebPromote: '',
          comment: '',
          editModifyDate: '2021/09/01 09:25:38',
          sourceWebName: 'Wen-Hsuan, Chang',
          startDate: '2021/06/20',
          endDate: '2021/09/30',
          hitRate: 110,
        },
        {
          version: '1.4',
          UID: '613c2241aaa3cf0fc41b9921',
          title: '跟你說一個秘密——蕭筑方．小倉薰作品展',
          category: '6',
          showInfo: [
            {
              time: '2021/09/10 00:00:00',
              location: '嘉義市*線上展覽',
              locationName: '跟你說一個秘密——蕭筑方．小倉薰作品展',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/10 00:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '「來，耳朵靠過來，跟你說一個秘密！」在這個疫情時代下，這可能已經變成一個無法輕易達成的動作。但是我們仍可以透過各式各樣的通訊工具，來訴說或是聆聽秘密。此次線上展，邀請到擅長以一種輕嘆語調呈現作品的兩位女性作家——蕭筑方和小倉薰，來告訴您他們的秘密。\r\n\r\n蕭筑方的創作題材皆來自於生活，透過簡單俐落的線條、大膽的配色，將當下的情緒和簡單平凡的現實生活轉化爲詼諧幽默的想像。近年接觸陶藝後，讓她的筆觸有了變化，拋開近乎潔癖式的完美線條，以一種更輕鬆自然的方式呈現。觀看蕭筑方的作品，就像在閱讀她的生活紀錄，能夠窺視到她內心的小秘密，走進她創造出的另一個世界。\r\n\r\n大學時期專攻雕塑的小倉薰嘗試過許多媒材，最後土與釉藥成為其表現基礎。近年創作不斷內化，從充滿肌理的人物場景，發展出一系列以陶與金工共置的形上空間。但比較少見的是她的平面作品，此次線上展展出的平面畫作，其明快的簡潔線條，也一直延續到她後來的創作上。來自生活的創作主題，儘管簡單平凡，卻充滿了暖暖的情感溫度。\r\n\r\n蕭筑方・小倉薰作品展，在現今這個充滿壓力、緊張的疫情時代，邀請您一同透過從生活延伸出的奇幻創作，發現只屬於自己的小秘密。',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D11/E112/F963/0a550baa-6188-4042-9788-5028b1c3bf73.jpg',
          masterUnit: [
            '泰郁 美學・堂',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: '',
          sourceWebPromote: 'http://www.taiyugallery.com.tw/itsbetweenyouandme.html',
          comment: '本次展覽為線上展覽',
          editModifyDate: '',
          sourceWebName: '泰郁藝術人文',
          startDate: '2021/09/10',
          endDate: '2021/10/10',
          hitRate: 326,
        },
        {
          version: '1.4',
          UID: '612f65b7aaa3cf0fc41b990b',
          title: '第二屆「音為愛」合唱詞曲創作比賽線上推廣講座',
          category: '7',
          showInfo: [
            {
              time: '2021/09/25 13:30:00',
              location: '臺北市大安區敦化南路一段159號3樓',
              locationName: 'ZOOM線上會議軟體',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/25 15:00:00',
            },
            {
              time: '2021/09/25 15:30:00',
              location: '臺北市大安區敦化南路一段159號3樓',
              locationName: 'ZOOM線上會議軟體',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/25 17:00:00',
            },
            {
              time: '2021/10/16 13:30:00',
              location: '臺北市大安區敦化南路一段159號3樓',
              locationName: 'ZOOM線上會議軟體',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/16 15:30:00',
            },
            {
              time: '2021/10/16 16:00:00',
              location: '臺北市大安區敦化南路一段159號3樓',
              locationName: 'ZOOM線上會議軟體',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/16 17:30:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '「音為愛 Sing For Love」計畫致力於將公益慈善理念寄寓藝文創作之中，第二屆合唱詞曲創作比賽，秉持一貫的公益精神，以「臺灣人文地景」、「開啟機會之門」為題，從近百件作品中，選出混聲合唱、同聲合唱、兒童合唱、最佳作詞等獎項，共計14件優勝作品。\r\n\r\n第二屆「音為愛」系列推廣講座，邀請了台灣合唱推手翁佳芬、全方位音樂家陳樹熙、金曲獎最佳作詞人武雄，為大家一解樂曲詮釋、詞曲創作的奧秘。歡迎合唱指揮、各級學校教師、社團指導與愛樂人士共同加入「音為愛」推廣行列，成為優秀作品的推廣種子，將正向的力量匯聚延續！',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D1/E194/F64/d8ab43e2-4a8a-40ea-a1b8-a5d364d1d82f.jpg',
          masterUnit: [
            '台北室內合唱團',
          ],
          subUnit: [],
          supportUnit: [
            '台北市政府文化局、國藝之友會前會長張順立先生、國際扶輪3521地區總監馬長生先生、音為愛發起人暨國際扶輪3521地區前總監王光明先生、台北市北區扶輪社、台北關渡扶輪社、歐瑞雲女士​',
          ],
          otherUnit: [],
          webSales: 'https://www.accupass.com/go/taiwansingforlovetwo',
          sourceWebPromote: 'http://www.tcschoir.org.tw/production5',
          comment: '',
          editModifyDate: '',
          sourceWebName: '台北室內合唱團',
          startDate: '2021/09/25',
          endDate: '2021/10/16',
          hitRate: 24,
        },
        {
          version: '1.4',
          UID: '611dc403aaa344fef22fb333',
          title: '織塑巧色樂-臺灣工藝技法與創作展',
          category: '6',
          showInfo: [
            {
              time: '2021/08/15 00:00:00',
              location: '臺中市線上展覽',
              locationName: '線上展覽',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/12/31 00:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '免費',
          descriptionFilterHtml: '一個臺灣、五大主題、十三位人間國寶。\r\n用純粹的手藝，編織出創作者的心\r\n用經驗與時間的累積，堆疊出令人嘆為觀止的作品\r\n以文資教育的角度，走進十三位國家級藝師的情感層面，看見生命中的踏實與堅持，看見在傳統與現代的碰撞下思考出的創新，看見活到老學到老的精神。\r\n我們期待透過展覽，讓更多人對文資文化有所認識，讓更多人感受傳統工藝的美妙之處。\r\n\r\n指導單位 — 文化部\r\n主辦單位 — 文化部文化資產局\r\n執行單位 — 國立臺中科技大學\r\n展出藝師 — 依姓氏筆畫排序\r\n王清霜、李秉圭、李榮烈、林吳素霞、柯進多、張憲平、梁紹英、陳萬能、陳錫煌、傅明光、黃蘭葉、楊秀卿、劉千韶',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/cms/image/A0/B0/C0/D19/E103/F910/20cb8d1a-1367-4e5f-b969-5bf40ce1fade.jpg',
          masterUnit: [
            '文化部文化資產局',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [
            '指導單位: 文化部、執行單位: 國立臺中科技大學',
          ],
          webSales: '',
          sourceWebPromote: 'https://tcce.1916.org.tw/',
          comment: '',
          editModifyDate: '2021/09/01 09:26:02',
          sourceWebName: '李伊珊',
          startDate: '2021/08/15',
          endDate: '2021/12/31',
          hitRate: 48,
        },
        {
          version: '1.4',
          UID: '611f9a6cd083a31df0012bee',
          title: '偶藝喔咿喔~~布袋戲線上講座~~',
          category: '7',
          showInfo: [
            {
              time: '2021/08/28 19:00:00',
              location: '111  臺北市士林區文林路751號',
              locationName: '臺灣戲曲中心(詳見活動介紹)',
              onSales: 'N',
              price: '',
              latitude: '25.1023211',
              longitude: '121.5196346',
              endTime: '2021/08/28 19:00:00',
            },
            {
              time: '2021/09/04 19:00:00',
              location: '111  臺北市士林區文林路751號',
              locationName: '臺灣戲曲中心(詳見活動介紹)',
              onSales: 'N',
              price: '',
              latitude: '25.1023211',
              longitude: '121.5196346',
              endTime: '2021/09/04 19:00:00',
            },
            {
              time: '2021/09/11 19:00:00',
              location: '111  臺北市士林區文林路751號',
              locationName: '臺灣戲曲中心(詳見活動介紹)',
              onSales: 'N',
              price: '',
              latitude: '25.1023211',
              longitude: '121.5196346',
              endTime: '2021/09/11 19:00:00',
            },
            {
              time: '2021/09/18 19:00:00',
              location: '111  臺北市士林區文林路751號',
              locationName: '臺灣戲曲中心(詳見活動介紹)',
              onSales: 'N',
              price: '',
              latitude: '25.1023211',
              longitude: '121.5196346',
              endTime: '2021/09/18 19:00:00',
            },
            {
              time: '2021/09/25 19:00:00',
              location: '111  臺北市士林區文林路751號',
              locationName: '臺灣戲曲中心(詳見活動介紹)',
              onSales: 'N',
              price: '',
              latitude: '25.1023211',
              longitude: '121.5196346',
              endTime: '2021/09/25 19:00:00',
            },
          ],
          showUnit: '國立傳統藝術中心',
          discountInfo: '',
          descriptionFilterHtml: ' 課程簡介 \r\n\r\n由臺北木偶劇團的演師以「戲偶與真人」的互動，在線上帶領觀眾認識多元豐富的布袋戲世界。\r\n\r\n\r\n\r\n\r\n\t\r\n\t\t\r\n\t\t\t場次\r\n\t\t\t主題\r\n\t\t\t內容\r\n\t\t\r\n\t\t\r\n\t\t\t第一講\r\n\t\t\t8/28(六)\r\n\t\t\t偶~原來這是布袋戲\r\n\t\t\t\r\n\t\t\t臺灣布袋戲概況與種類介紹\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t第二講\r\n\t\t\t9/04(六)\r\n\t\t\t\r\n\t\t\t布袋戲LIVE BAND\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t布袋戲音樂：後場編制、樂器、與演師的搭配\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t第三講\r\n\t\t\t9/11(六)\r\n\t\t\t生旦淨末丑，通通都是我\r\n\t\t\t\r\n\t\t\t布袋戲腳色介紹與口白藝術：五音變化\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t第四講\r\n\t\t\t9/18(六)\r\n\t\t\t裝潢偶家大作戰\r\n\t\t\t\r\n\t\t\t布袋戲場景：彩樓、布景、道具與特效\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t第五講\r\n\t\t\t9/25(六)\r\n\t\t\t看布袋戲需要充滿想像力\r\n\t\t\t\r\n\t\t\t布袋戲操偶與寫意表現手法\r\n\t\t\t\r\n\t\t\r\n\t\r\n\r\n\r\n\r\n\r\n \r\n\r\n 課程資訊 \r\n\r\n◇ 時間：週六晚間19:00-19:30\r\n◇ 播出：臺灣戲曲中心facebook直播\r\n◇ 活動專線：02-8866-9600#1643 黃小姐\r\n\r\n \r\n\r\n\r\n\r\n 團隊成員 \r\n\r\n\r\n團長｜林永志\r\n藝術總監｜伍姍姍\r\n前場演師｜吳聲杰、陳思廷、廖群瑋、林瑞騰\r\n後場樂師｜謝彤妍、張慈欣、廖子婷、林育慶、林宸弘\r\n特別來賓｜洪澤南老師\r\n行政統籌｜謝琼崎\r\n道具陳設｜林璟丞、王祥亮\r\n直播、拍攝｜鼎珅國際整合行銷股份有限公司\r\n\r\n \r\n\r\n\r\n 演出團隊│臺北木偶劇團 \r\n\r\n臺北木偶劇團成立於2010年，以保存傳統偶戲表演藝術，提升偶戲表演素質為創立宗旨，為臺灣具活力的新生代木偶劇團之一。近幾年持續尋找傳統、發掘傳統，發揮過去習藝時所累積的豐富經驗，以認真、用心的製作方針，在不拘泥于傳統木偶劇之創作形式下，以多元及多變的木偶劇場藝術特色，創作出更細膩、精緻的表演方式，吸引更多觀眾走進劇場感受不同以往的布袋戲饗宴。\r\n\r\n \r\n\r\n承辦單位：臺北木偶劇團\r\n主辦單位：國立傳統藝術中心\r\n指導單位：文化部\r\n*更多相關資訊隨時更新\r\n*主辦單位保有節目異動的權利',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/XCT_10052/d8cec2e77a00016144127f65541120696d66810f.jpg',
          masterUnit: [
            '臺灣戲曲中心',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/XCT/portal/Registration/C0103MAction?actId\u003d10052',
          sourceWebPromote: 'https://event.culture.tw/XCT',
          comment: '',
          editModifyDate: '2021/09/01 09:20:47',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/08/28',
          endDate: '2021/09/25',
          hitRate: 60,
        },
        {
          version: '1.4',
          UID: '613603d3d083a31df0013178',
          title: '走讀嘉蘭2‧徑入依麻林道，森心香癒說故事（110年度文化部世界閱讀日「走讀臺灣」）',
          category: '7',
          showInfo: [
            {
              time: '2021/09/26 14:00:00',
              location: '',
              locationName: '線上',
              onSales: 'Y',
              price: '0',
              latitude: null,
              longitude: null,
              endTime: '2021/09/26 14:00:00',
            },
            {
              time: '2021/09/26 15:30:00',
              location: '',
              locationName: '線上',
              onSales: 'Y',
              price: '250',
              latitude: null,
              longitude: null,
              endTime: '2021/09/26 15:30:00',
            },
          ],
          showUnit: '國立臺灣史前文化博物館',
          discountInfo: '',
          descriptionFilterHtml: '位於臺東縣的金峰鄉嘉蘭社區，這裡由七個排灣族部落與一個魯凱族部落遷移組成，同時有著排灣與魯凱族的母體文化，運轉著獨特的社會慣習與在地知識，Maljivel馬里弗勒部落便是其中一個排灣族部落。\r\n〈巴里的紅眼睛〉這則故事在各部落間流傳著不同的口述版本，而在Maljivel馬里弗勒部落的口述歷史裡，故事所述地點就位於部落第一遷移舊遺址Kinaaulje奇拿奧勒，在這個版本，主角的名字是puljaljuyan（卜拉路揚）。\r\n事實上，在排灣族的語言裡，palji巴里的意思是指具有異於一般人能力的異能者、超凡能力者，在某方面具有特殊的強大功能。在不同部落、不同文化、不同家族的歷史，自古以來都有關於各種神力palji巴里的故事流傳著。\r\n在這次課程，我們先跟著影片來到部落入口處前面，聽部落傳統領袖與部落主席在象徵七個部落、一個聚落的八大柱前面，告訴大家各部落的遷徙由來。\r\n接著跟著族人經過依麻林道，來到Maljivel 馬里弗勒部落遺址。這裡的遺址石堆代表祖靈的居所就在石板屋底下，那麼何以Maljivel 馬里弗勒部落會遷移呢？部落主席會告訴我們。\r\n部落主席還要告訴我們以前的vuvu長輩他們在這裡生活的山林智慧，黃藤可說是編織聖物，楓樹林猶如跳躍的滿天星，在以前被當作愛情麵包來看待的九芎，以及象徵著紅眼睛巴里的守護─檳榔。\r\n芳療師也將介紹林道上的島嶼植物，環抱林道的臺灣杉木、守護身心的紅豆杉、生薑則象徵vuvu給的溫暖。儘管遷移離開舊部落，與此地緊密連結的臍帶還是維繫著。\r\n上半場結束前，來聆聽少年結合圖畫與配音的創作，說出紅眼睛巴里的故事。\r\n下半場，打開收到的植物精油材料包，一起跟著芳療師進行自然植物精油的聞香調油DIY。運用影片裡常於林間見到的生薑，動手調製與土地連結的薑為基底，搭配甜橙、歐薄荷的複方按摩精油（容量10ml），運用香氣成份有尤加利、薰衣草、白千層的複方精油調製芳香洗手慕斯（容量300ml），透過植物的香氣，直接感受林道與舊部落給予我們的溫暖力量。\r\n\r\n\r\n參考文本\r\n\r\n《排灣族：巴里的紅眼睛：台灣原住民的神話與傳說（四）》新自然主義出版\r\n\r\n\r\n講師群\r\n\r\nkuljelje·giring   吳善德／Maljivel馬里弗勒部落mamazangiljan\r\ncapadis·djuljapalas   林溫金枝／Maljivel馬里弗勒部落耆老\r\npuljaluyan·ljeleman   鐘阿元／Maljivel馬里弗勒部落耆老\r\nvavui·tjaluljivak   黃志明／嘉蘭村部落主席、Maljivel馬里弗勒部落執行長、卜拉米─喇响小棧解說員\r\nmasgesge·badjaljinuk   馬斯戈斯戈‧霸加里努克／cuvuq芽劇場\r\nTauwan   高渟筑／茉莉二號文化工作室\r\n\r\n \r\n\r\n\r\n活動費用\r\n\r\n只有參加上半場者，線上收看免費。\r\n繼續參加下半場者，請匯款250元（自然精油調香DIY材料包宅配到府，含運原價500元。材料包內容為10ml基礎油、起泡劑、容量為300ml的慕斯瓶、單方精油3款各1ml、複方精油5ml、聞香試紙等，可製成兩項成品：按摩精油與芳香洗手慕斯）\r\n※此為材料包示意圖。\r\n\r\n\r\n\r\n\r\n課程流程\r\n\r\n13:30〜14:00 學員上線\r\n14:00〜15:30 主持人masgesge介紹\r\n                    觀看部落影片：八大部落遷徙由來\r\n                    觀看部落影片：Maljivel馬里弗勒部落遺址\r\n                    觀看部落影片：vuvu 的山林智慧篇\r\n                    觀看部落影片：林道上的島嶼植物\r\n                    聽紅眼睛巴里的故事\r\n                    （上半場學員下線，下半場學員繼續參加）\r\n15:30〜17:00 自然精油聞香調油DIY、問題討論交流',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/NMP_10051/57ce99bae7e56442fbbbb403457966c681ada3be.jpg',
          masterUnit: [
            '國立臺灣史前文化博物館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'http://event.culture.tw/NMP/portal/Registration/C0103MAction?actId\u003d10051',
          sourceWebPromote: 'http://event.culture.tw/NMP',
          comment: '',
          editModifyDate: '2021/09/07 09:53:54',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/26',
          endDate: '2021/09/26',
          hitRate: 31,
        },
        {
          version: '1.4',
          UID: '6145d5d8d083a31df00135fa',
          title: '瑜伽•愉家：森心靈的平靜力量',
          category: '19',
          showInfo: [
            {
              time: '2021/09/25 10:00:00',
              location: '',
              locationName: 'Google Meet平台',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/28 14:00:00',
            },
          ],
          showUnit: '指導單位：文化部、行政院環境保護署環境保護人員訓練所；主辦單位：國立臺灣博物館',
          discountInfo: '',
          descriptionFilterHtml: '🌷 活動對象：15歲高中以上一般民眾。一場30名。\r\n\r\n🌷 活動地點：Google Meet平台、手機App（⭐參與者需有google信箱帳號⭐）。\r\n\r\n🌷 注意事項：詳細資訊請見下方報名資訊。\r\n\r\n\r\n\t需自行準備瑜珈墊、擦汗毛巾、瑜珈磚。並穿著易伸展衣服。\r\n\t須開啟視訊鏡頭，講師會隨時注意參與者狀況。\r\n\t室內溫度約設在28度左右，保持通風。\r\n\t活動前2天寄發行前信(含連結、代碼)。\r\n\t⭐因近期多次發生不同郵件系統將本館信件移至垃圾信件之事件，請您適時留意垃圾信箱。若您於活動前1天仍未收到信件，請您聯繫活動承辦人，謝謝您！⭐\r\n\r\n\r\n🌷 場次時間：\r\n\r\n\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t時間\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t主題及內容簡介\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t講師\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t9/25(六)\r\n\r\n\t\t\t10:00-11:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t舒緩瑜伽1\r\n\r\n\t\t\t*初學者友善\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t Ashley 老師\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t9/27(一)\r\n\r\n\t\t\t14:00-15:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t舒緩瑜伽2\r\n\r\n\t\t\t*初學者友善\r\n\t\t\t\r\n\t\t\t\r\n\t\t\tAshley 老師\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t9/27(一)\r\n\r\n\t\t\t15:30-16:30\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t輕流動瑜伽1\r\n\r\n\t\t\t*適合有基礎者\r\n\t\t\t\r\n\t\t\t\r\n\t\t\tAshley 老師\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t9/28(二)\r\n\r\n\t\t\t14:00-15:00\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t輕流動瑜伽2\r\n\r\n\t\t\t*適合有基礎者\r\n\t\t\t\r\n\t\t\tAshley 老師\r\n\t\t\r\n\t\r\n\r\n\r\n🌷 講師簡介：請點我\r\n\r\n ',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/NTM_12222/ea1f29a5054a292fa81f262466923d0878bdc1a8.jpg',
          masterUnit: [
            '國立臺灣博物館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/NTM/portal/Registration/C0103MAction?actId\u003d12222',
          sourceWebPromote: 'https://event.culture.tw/NTM',
          comment: '',
          editModifyDate: '2021/09/22 14:25:45',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/25',
          endDate: '2021/09/28',
          hitRate: 13,
        },
        {
          version: '1.4',
          UID: '613c9b56d083a31df0013389',
          title: '2021全國古蹟日「仙人走獸」Instagram濾鏡',
          category: '15',
          showInfo: [
            {
              time: '2021/09/18 00:00:00',
              location: '',
              locationName: '線上',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/30 00:00:00',
            },
          ],
          showUnit: '國立中正紀念堂管理處',
          discountInfo: '',
          descriptionFilterHtml: '  中正紀念堂仙人走獸Instagram濾鏡\r\n\r\n\r\n\r\n許多傳統宮殿式建築的簷角上，有著以仙人騎鳳領軍的各式走獸，\r\n\r\n今年古蹟日特別推出以中正紀念堂的屋頂上六款可愛的「仙人走獸」設計的IG濾鏡，\r\n\r\n透過趣味的方式認識這些小神獸。\r\n\r\n快拿起手機開啟限時動態搜尋「仙人走獸」或搜尋中正紀念堂官方IG帳號「CKSMH」\r\n\r\n來看看你是哪隻走獸吧！',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/CKSMH_10433/d7e001499d411b9771854c34032358730c8d2dfa.jpg',
          masterUnit: [
            '國立中正紀念堂管理處',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/CKSMH/portal/Registration/C0103MAction?actId\u003d10433',
          sourceWebPromote: 'https://event.culture.tw/CKSMH',
          comment: '',
          editModifyDate: '2021/09/13 11:22:45',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/18',
          endDate: '2021/09/30',
          hitRate: 20,
        },
        {
          version: '1.4',
          UID: '613c9b55d083a31df0013387',
          title: '2021全國古蹟日「探古尋今繪圖趣」(活動總說明)',
          category: '15',
          showInfo: [
            {
              time: '2021/09/18 09:00:00',
              location: '',
              locationName: '線上',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/30 09:00:00',
            },
          ],
          showUnit: '國立中正紀念堂管理處',
          discountInfo: '',
          descriptionFilterHtml: '2021全國古蹟日「探古尋今繪圖趣」系列活動        \r\n\r\n★9/18準時開跑★\r\n\r\n\r\n\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t項次\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t活動類別/內容\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t參加費用\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t參加對象\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t1\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t線上古蹟導覽-探古尋今\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t免費\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t一般民眾\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t2\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t線上寫生-繪圖趣(採網路報名)\r\n\t\t\t\r\n\t\t\r\n\t\t\r\n\t\t\t\r\n\t\t\t3\r\n\t\t\t\r\n\t\t\t\r\n\t\t\t中正紀念堂仙人走獸Instagram濾鏡\r\n\t\t\t\r\n\t\t\r\n\t\r\n\r\n\r\n活動說明:\r\n\r\n第一站:線上古蹟導覽-探古尋今\r\n\r\n中正紀念堂的故事等著您的「探尋」💖\r\n\r\n此次邀請鄭勝吉老師拍攝導覽影片\r\n\r\n透過中正紀念堂官方Facebook粉絲團觀賞\r\n\r\n以中正紀念堂為主題，講解其歷史發展與建築特色\r\n\r\n在疫情期間透過線上影片觀賞\r\n\r\n帶領民眾欣賞國定古蹟及文化景觀，傳承文化資產保存理念\r\n\r\n請上中正紀念堂官方FB粉絲團觀賞\r\n\r\n貼心小提醒:恭喜完成第一站，請前往下一站「線上古蹟寫生-繪圖趣」!\r\n\r\n \r\n\r\n \r\n\r\n第二站:線上寫生-繪圖趣\r\n\r\n看完探古尋今-古蹟導覽\r\n\r\n是時候發掘潛藏的藝術細胞\r\n\r\n現在只要🖍「動筆繪畫」🖍你對中正紀念堂的旅遊視角\r\n\r\n上傳到個人FB或IG及Hashtag「#探古尋今繪圖趣」(須追蹤本處官方FB或IG)\r\n\r\n完成後可獲贈精美紀念品\r\n\r\n活動報名\r\n\r\n貼心小提醒:最後一站即將抵達，加快您的腳步，前往第三站中正紀念堂仙人走獸IG濾鏡\r\n\r\n     第三站:中正紀念堂仙人走獸Instagram濾鏡\r\n\r\n你知道嗎?\r\n\r\n    中正紀念堂建築屋頂上的六款「仙人走獸」吉祥物\r\n\r\n          (仙人騎鳳、天馬、海馬、龍、鳳和獅子)\r\n\r\n已經正式加入IG濾鏡的行列\r\n\r\n快拿起手機開啟限時動態搜尋「仙人走獸」\r\n\r\n來看看你是哪隻走獸~~\r\n\r\n \r\n\r\n貼心小提醒:恭喜你!已經完成「探古尋今繪圖趣」的旅途，請不要忘記前往終點站挑戰領取中正紀念堂愛心小禮物~~\r\n\r\n \r\n\r\n終點站:精美禮物兌換站👍\r\n\r\n兌換區1:影片問答抽抽樂~\r\n\r\n老師說的話，有沒有注意聽呢?\r\n\r\n現在要考考大家，導覽影片中老師的3個提問\r\n\r\n快到影片下方留言回答正解，並標註(Tag)一位朋友\r\n\r\n即可參加抽獎活動。\r\n\r\n就有機會獲得〝中正紀念堂建築藍圖明信片〞\r\n\r\n(將於10/1抽出50位幸運得主，並於網站公告)\r\n\r\n \r\n\r\n \r\n\r\n兌換區2:繪圖趣，去換禮!\r\n\r\n完成中正紀念堂的畫作後\r\n\r\n不要忘記將充滿藝術的畫作放到個人FB或IG\r\n\r\n並＃探古尋今繪圖趣(記得追蹤本處FB或IG)\r\n\r\n完成後可獲贈精美紀念品~~\r\n\r\n \r\n\r\n為響應全國古蹟日，9月18日至9月26日本處亞熱帶公司\r\n\r\n（含禮品店、咖啡吧、華香餐廳及TeaHouse）\r\n\r\n購買「台灣微笑標章」商品消費滿新台幣1,000元，即贈送精美小禮物(送完為止)、\r\n\r\n靜思書軒出版品9折優惠，滿千再送福袋喔！\r\n\r\n ',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/CKSMH_10430/d7e001499d411b9771854c34032358730c8d2dfa.jpg',
          masterUnit: [
            '國立中正紀念堂管理處',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/CKSMH/portal/Registration/C0103MAction?actId\u003d10430',
          sourceWebPromote: 'https://event.culture.tw/CKSMH',
          comment: '',
          editModifyDate: '2021/09/13 11:23:07',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/18',
          endDate: '2021/09/30',
          hitRate: 23,
        },
        {
          version: '1.4',
          UID: '60f6addcd083a31e44959b02',
          title: '2021 / 9 / 30 Francesca Vailati Online Lecture',
          category: '15',
          showInfo: [
            {
              time: '2021/09/30 15:00:00',
              location: ' 線上 ',
              locationName: 'GoToWebinar',
              onSales: 'Y',
              price: '2,000',
              latitude: '23.972',
              longitude: '120.9777',
              endTime: '2021/09/30 18:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '!!! 請注意, 非常重要!!! \r\n報名繳費完成後後、請於Facebook上搜尋 " 2021/09/30 Francesca Vailati Online Lecture TW " 或由此連結進入 https://www.facebook.com/groups/1000035570759687 ,主動要求加入到 FB 私密社團，所有課程訊息及觀看課程方式將於私密社團內即時公告, 請務必加入 謝謝配合~  \r\n*尊重講師著作財產權, 本線上演講不做錄影回播，請務必在直播時間加入會議觀看* \r\n  \r\n!!!Important Announcement!!! \r\nAs your online registration completed, please search for Facebook private group name " 2021/09/30 Francesca Vailati Online Lecture TW " or enter the provided link https://www.facebook.com/groups/1000035570759687 and ask to join the private group for all further course official annoucements, which contains course login procedures required.  \r\n*As respect to the lecturer\u0027s copyright and property rights, this online speech will not be recorded and played back. Please be sure to join the conference during the live broadcast schedule* \r\n  \r\n  \r\n \r\nFrancesca Vailati MD, DMD, MSc \r\n  \r\nAfter receiving her medical degree from the University of Bari (Italy) in 1996, Dr. Vailati left Europe to pursue her dental education in the United States. In 2000 she received her dental degree from the University of Pennsylvania (USA) and in 2003, she earned a certificate in Prosthodontics along with with a M.S.D. degree from the University of Connecticut (USA). Returning to Europe in 2004, she joined the department of Fixed Prosthodontic headed by Prof. Urs Belser at the University of Geneva (Switzerland), until 2020. Dr. Vailati maintains a part-time private practice in Geneva, dedicated to rehabilitation of worn down dentitions, using adhesive Prosthodontics and ADDITIVE Dentistry. She has developed a protocol, the 3STEP technique, which allows clinicians to face full-mouth rehabilitations in a more predictable manner. Finally, Dr. Vailati has created her own Academy, the 3STEP Academy, with different centres around Europe. Her main location, however, remains on the Lake Como, Italy, where theoretical-practical courses are held on Additive Prosthodontics and functional rehabilitation of patients affected by erosion and dysfunction. \r\n  \r\n自2002年 Dr. Pascal Magne 和 Prof. Urs Belser 發表 “Bonded Porcelain Restorations” 一書起，黏著性的贋復治療開始成為贋復治療的顯學，而 Dr. Francesca Vailati 與 Prof. Urs Belser 其後於 2008 發表的三篇關於全口重建運用3-step techniques文章，更讓黏著性處理方式躍上另一個閃耀台階，很快席捲了全世界，開啟更廣泛、也更幫助病患的方式。個人在2016年兩度參加 Dr. Vailati 在 Barcelona 的完整課程，也在2018年帶團參加她在法國 Annecy 的開立的課程，每次都有深刻的啟發。我內心最大的感想，就是 Francesa 她總是站在病友的角度，思考何種的治療能為病友帶來最大的好處；而她努力衝撞牙醫界各種不平等，例如性別不平等、頑固學究思想的禁銬...等等，更加凸顯她不願妥協與追求真理的豪爽個性！ \r\n臺灣牙醫界何等有幸在2021年九月底有這個機會，迎接世界傑出女牙醫師的演講。她帶來的，不但是牙醫治療方向與技術上的突破，引領更好的方向，重要的是，她代表的意義：女性同樣也能作爲領導人、同樣在牙醫界也能和男性一樣有重大的貢獻！ \r\n歡迎各位牙醫師參加，也更鼓勵年輕女牙醫們的參加，也期待臺灣牙醫界有更多的女力發光發熱！👍 \r\n彭炯熾 2021 \r\n  \r\n報名方式 / Registration：KKTIX.com    \r\n售票期間 / Registration Deadline: 9/23, 23:59   (September 23, 23:59) \r\n播放時間 / Course Live on : September 30, 15:00 ~ 18:00 (Taipei Time) \r\n收看方式 / Broadcast Application：GoToWebinar \r\n\n 如有問題請聯絡學會 / APD contact info :  prosthor@ms48.hinet.net / (02) 2546-8834 \r\n  \r\n注意事項: \r\n \r\n 請注意勿重複購買，購買之後恕不退費 \r\n 線上演講可於播出當天下午三點至六點觀看，本次線上演講共三學分 \r\n \r\n  \r\n\n *No refunds as your registration completes* \r\n*本活動報名後將無法提供退費 謝謝*',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/ed04b06f-907a-43b8-97f6-d54ee01386b2/df9218f7/4f767e878a66b7de77f5544c1b6fea33e8558729.jpg',
          masterUnit: [
            '中華民國贋復牙科學會 (APD ROC)',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://kktix.com/events/df9218f7/registrations/new',
          sourceWebPromote: 'https://kktix.com/',
          comment: '',
          editModifyDate: '2021/09/01 09:13:40',
          sourceWebName: 'KKTIX',
          startDate: '2021/09/30',
          endDate: '2021/09/30',
          hitRate: 74,
        },
        {
          version: '1.4',
          UID: '611f9a54d083a31df0012beb',
          title: '2021國際漫畫系列講座《探尋與對話：閱讀世界中的漫畫》',
          category: '7',
          showInfo: [
            {
              time: '2021/09/04 14:00:00',
              location: '',
              locationName: 'YouTube線上直播',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/04 14:00:00',
            },
            {
              time: '2021/09/14 14:00:00',
              location: '',
              locationName: 'YouTube線上直播',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/09/14 14:00:00',
            },
            {
              time: '2021/10/01 13:00:00',
              location: '',
              locationName: 'YouTube線上直播',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/01 13:00:00',
            },
            {
              time: '2021/10/02 13:00:00',
              location: '',
              locationName: 'YouTube線上直播',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/02 13:00:00',
            },
            {
              time: '2021/10/03 10:00:00',
              location: '',
              locationName: 'YouTube線上直播',
              onSales: 'N',
              price: '',
              latitude: null,
              longitude: null,
              endTime: '2021/10/03 10:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '關於《探尋與對話：閱讀世界中的漫畫》\r\n\r\n在2021國際漫畫系列講座中，國家漫畫博物館籌備小隊邀請了來自臺灣、英國、法國、比利時、日本、韓國、香港、馬來西亞的漫畫產業人士、學者、創作者等專家，以線上講座的方式開啟跨域對話，一同探尋多元的漫畫文化，從各國漫畫題材聊到漫畫博物館，眾多豐富主題的講座即將開跑！跟著我們一起閱讀世界中的漫畫吧！\r\n\r\n \r\n\r\n線上講座\r\n\r\n ▶直播平臺：「國家漫畫博物館籌備小隊」YouTube 頻道\r\n\r\n ▶活動需事先報名，直播網址將於活動前寄送至報名成功者之電子信箱\r\n\r\n ▶Youtube直播時外國講者將以中文口譯播出（非講者原聲）\r\n\r\n ▶另為外語觀眾提供「原聲會議室」收聽外國講者原聲 (為語音頻道)，會議室連結將隨YouTube直播觀看連結一併提供。\r\n\r\nYoutube live streams provide Mandarin simultaneous interpretation only,while the “Original Voices Rooms” provide original voice from speakers.(Both links will be sent by email before each event.)\r\n\r\n \r\n\r\n📚【分享講座1：漫畫X博物館】\r\n\r\n時間：9月4日（六） 14:00-17:00\r\n\r\n引言人：國立臺灣歷史博物館館長張隆志\r\n\r\n講者：\r\n\r\n◆ 日本京都國際漫畫博物館研究員Yoo Sookyung\r\n\r\n◆ 法國安古蘭國際漫畫暨影像城館長Pierre Lungheretti\r\n\r\n◆ 比利時布魯塞爾漫畫藝術中心館長Isabelle Debekker\r\n\r\n簡介：博物館存在意義與價值是文化精神的體現，透過場域與氛圍爬梳文化與歷史的脈絡。而漫畫博物館，將其視覺文化透過展示、典藏、研究和教育，引導民眾認識漫畫敘事背後的理念，這次的講座邀請來自日本、法國、比利時的漫畫博物館專家們，一同探討漫畫博物館背後營運與文化理念。\r\n\r\n \r\n\r\n📚【分享講座2：漫畫X社群】\r\n\r\n時間：9月14日（二） 14:00-16:40\r\n\r\n引言人：開拓動漫祭執行長蘇微希\r\n\r\n講者：\r\n\r\n◆ 韓國漫畫影像振興院博物館營運組組長Kim Bo-Guem\r\n\r\n◆ 法國布洛瓦BD BOUM漫畫節總監Bruno Génini\r\n\r\n簡介：隨著時代發展，漫畫作品露出的管道與平臺越來越多，在不同國家的社會文化背景下，呈現出各具特色的漫畫社群，這次的講座邀請來自韓國及法國的漫畫專家，分別以博物館及漫畫節的視角，分享其營運方式，探討漫畫社群的組成與連結。\r\n\r\n \r\n\r\n📚【學術講座1：漫畫題材面面觀】\r\n\r\n時間：10月1日（五） 13:00-17:30\r\n\r\n引言人：大人的漫畫社主持人陳怡靜\r\n\r\n講者：\r\n\r\n◆ 香港資深動畫人盧子英\r\n\r\n◆ 積木文化主編李華\r\n\r\n◆ 國立中央大學法文系副教授Ivan Gros 葛尹風\r\n\r\n◆ 馬來西亞藝術家NOvia Shin冼佩珊\r\n\r\n◆德國美茵茨大學翻譯、語言與文化學院研究暨教職人員陳蘊柔\r\n\r\n簡介：在不同文化背景下，漫畫從取材到內容呈現，各發展出獨到風格與魅力。在多元的漫畫題材中，也常映照出當地的社會及文化面貌，活動講者們分別以研究學者、編輯、創作者等視角，分享來自香港、德國、法國、馬來西亞等不同地區的漫畫創作題材及特色。\r\n\r\n \r\n\r\n📚【學術講座2：漫畫藝術視界】\r\n\r\n時間：10月2日（六） 13:00-17:30\r\n\r\n引言人：法文譯者/藝評家陳文瑤\r\n\r\n講者：\r\n\r\n◆ 插畫家/漫畫創作者阿尼默\r\n\r\n◆ 藝術家/漫畫創作者周依\r\n\r\n◆ 法國安古蘭歐洲高等圖像學院漫畫學程教授Johanna Schipper\r\n\r\n◆ 英國倫敦藝術大學倫敦傳播學院/Comic Research Hub教授Ian Horton\r\n\r\n◆ 漫畫評論家吳平稑\r\n\r\n簡介：漫畫是藝術嗎？漫畫被視為藝術形式之一，在歐洲也被稱為「第九藝術」。漫畫以涵蓋視覺、美學和文學等表現手法，傳達故事及意念，這次活動講者們分別以研究學者、評論家、創作者等觀點，分享來自法國、英國等不同地區的探討漫畫藝術發展，一同探索漫畫敘事藝術的魅力。\r\n\r\n \r\n\r\n📚【分享講座3：漫畫幕後編輯】\r\n\r\n時間：10月3日（日） 10:00-12:30\r\n\r\n講者：\r\n\r\n◆ 日本集英社《少年Jump+》副編輯長林士平\r\n\r\n◆ 黑白文化主編柏雅婷\r\n\r\n簡介：漫畫出版的背後，總少不了編輯們的幕後參與，除了與漫畫創作者溝通及書籍出版外，在數位時代中，漫畫編輯也面臨閱讀載體、媒體等各種新的改變。本次講座邀請日本和臺灣的漫畫產業編輯，以自身經歷分享其工作和漫畫編輯方法，帶我們一窺漫畫書背後的各種出版秘辛。\r\n\r\n \r\n\r\n注意事項\r\n\r\n▶活動前QA收集：如有問題想要詢問講師，歡迎填寫表單https://reurl.cc/yEqaa6，主辦單位將於活動前整理問題並提供給講師\r\n\r\n▶本次講座為非公開直播，影片將於當日結束後下架，請報名成功者於活動時間準時收看！\r\n\r\n \r\n\r\n2021國際漫畫系列講座《探尋與對話：閱讀世界中的漫畫》紀念品抽獎辦法\r\n\r\n1. 問卷填寫：講座結束後，畫面將顯示「活動問卷QR Code」10分鐘，影片留言區並同步提供活動問址連結，擇1填寫即可。完成問卷填寫者即獲得該場次抽獎資格。\r\n\r\n2. 抽獎：1場次抽出10位完成問卷填寫者，5場次計送出50份活動專屬紀念品。中獎名單將於系列活動結束後7天內於「國家漫畫博物館籌備小隊」臉書粉絲專頁公布。\r\n\r\n \r\n\r\n📍主辦單位保有修改、解釋及取消活動之權利，若有異動，以國立臺灣歷史博物館官方網站及國家漫畫博物館籌備小隊粉絲專頁之公告為準。\r\n\r\n📍國家漫畫博物館籌備小隊粉絲專頁：https://www.facebook.com/NationalComicMuseum',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/NMTH_10025/42859b69061b847add65aeeca30433ad48492432.jpg',
          masterUnit: [
            '國立臺灣歷史博物館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/NMTH/portal/Registration/C0103MAction?actId\u003d10025',
          sourceWebPromote: 'https://event.culture.tw/NMTH',
          comment: '',
          editModifyDate: '2021/09/01 09:20:31',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/04',
          endDate: '2021/10/03',
          hitRate: 65,
        },
        {
          version: '1.4',
          UID: '60e446c2d083a31e449599b4',
          title: '色線形-傅菊珠多彩之美創作展(線上展覽)',
          category: '6',
          showInfo: [
            {
              time: '2021/07/08 08:30:00',
              location: '950  臺東縣臺東市臺東市大同路254號',
              locationName: '國立臺東生活美學館生活工坊',
              onSales: 'N',
              price: '',
              latitude: '22.7552485',
              longitude: '121.1510514',
              endTime: '2021/10/04 08:30:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '色線形-傅菊珠多彩之美創作展，展期自110年7月8日至10月4日止（週二休館）於國立臺東生活美學館官網採線上影音展方式開放民眾瀏覽。生活工坊實體展覽俟中央流行疫情指揮中心微解封藝文場館，始開放民眾參觀，入館參觀民眾請全程戴口罩並保持安全社交距離。\r\n\r\n客籍染色藝術家傅菊珠老師，善於運用圖騰與各種花紋的組合，在傳統技術裡展現創新的活力，游刃有餘地遊走在染布、禪繞與拼布領域，每件作品都能夠讓人深刻感受到藝術家發自內心的真誠與喜悅，結合產業應用更是充滿無限商機，是少數能兼具藝術性與市場的創作風格。\r\n\r\n傅菊珠近年更將繽紛多彩染色結合在地節慶活動等，染出大型戶外創作作品，作品於2014年客庄十二大節慶臺東好米收冬季戶外展出，2015年受邀屏東縣全國客家日五彩補天大型染布藝術展…震撼你的視覺展出，2016年受聘擔任客庄十二大節慶臺東好米收冬季千人染布創意技術總監，2017年至今受聘擔任中國北京布流行手工學院繽紛多彩渲染簽約講師，2018年受邀廈門海峽文創園區拼布藝術聯展，2018年9月受邀上海第十屆亞洲拼布及編織節展，2019年4月受邀貴州丹塞蠟染刺繡手作交流聯展等。\r\n\r\n此次展出傅菊珠多年來的創作成果，作品以簡單的素材與環保型的染色工藝技法，結合拼布壓線的自由手推線條，呈現多層次色彩與精緻的立體效果，並以不同的形式貫穿共同主題，讓觀賞者感受色彩之美愉悅心情。\r\n\r\n線上影音展:https://imedia.culture.tw/channel/ttcsec/zh_tw/media/125794',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/TTCSEC_10018/7580cb324c68db21b9b75e41b86a12d2dd40090f.jpg',
          masterUnit: [
            '國立臺東生活美學館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/TTCSEC/portal/Registration/C0103MAction?actId\u003d10018',
          sourceWebPromote: 'https://event.culture.tw/TTCSEC',
          comment: '',
          editModifyDate: '2021/09/01 09:21:06',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/07/08',
          endDate: '2021/10/04',
          hitRate: 356,
        },
        {
          version: '1.4',
          UID: '610147ced083a31df0012544',
          title: '2021工藝講堂 「工藝與文創思潮系列講座」',
          category: '7',
          showInfo: [
            {
              time: '2021/08/14 14:00:00',
              location: '100  臺北市中正區南海路41號',
              locationName: '臺北當代工藝設計分館7F',
              onSales: 'N',
              price: '',
              latitude: '25.0318695',
              longitude: '121.5123708',
              endTime: '2021/08/14 14:00:00',
            },
            {
              time: '2021/09/04 14:00:00',
              location: '100  臺北市中正區南海路41號',
              locationName: '臺北當代工藝設計分館7F',
              onSales: 'N',
              price: '',
              latitude: '25.0318695',
              longitude: '121.5123708',
              endTime: '2021/09/04 14:00:00',
            },
            {
              time: '2021/09/11 14:00:00',
              location: '100  臺北市中正區南海路41號',
              locationName: '臺北當代工藝設計分館7F',
              onSales: 'N',
              price: '',
              latitude: '25.0318695',
              longitude: '121.5123708',
              endTime: '2021/09/11 14:00:00',
            },
            {
              time: '2021/10/23 14:00:00',
              location: '100  臺北市中正區南海路41號',
              locationName: '臺北當代工藝設計分館7F',
              onSales: 'N',
              price: '',
              latitude: '25.0318695',
              longitude: '121.5123708',
              endTime: '2021/10/23 14:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '2021工藝講堂 「工藝與文創思潮系列講座」(8-10月)\r\n\r\n一、8月份\r\n\r\n       講座主題：「Form Follows Story 型隨在地」\r\n\r\n       講座時間：8/14(六)14:00-17:00\r\n\r\n       主講人：吳孝儒 (無氏製作 PiliWu-Design  創辦人)\r\n\r\n二、9月份\r\n\r\n(一) 講座主題：「從玻璃到公共藝術」\r\n\r\n       講座時間：9/4(六)14:00-17:00\r\n\r\n       主講人：張全成 (國立清華大學藝術與設計系退休教授/張全成琉璃工作室負責人)\r\n\r\n(二) 講座主題：「柳岸花明-臺灣文創工藝的傳承與創新」\r\n\r\n       講座時間：9/11(六)14:00-17:00\r\n\r\n       主講人：李福源 (大同大學工業設計學系副教授/般若文創設計公司創辦人)\r\n\r\n三、10月份\r\n\r\n       講座主題：「器物與空間的對話」\r\n\r\n       講座時間：10/23(六)14:00-17:00\r\n\r\n       主講人：鄭志仁(晴山傢俱 Armani Casa 藝術總監 /三井餐飲集團美學總監)\r\n\r\n四、以上講座地點: 臺北當代工藝設計分館7樓 (臺北市中正區南海路41號)\r\n\r\n五、報名方式：\r\n\r\n(一)有關2021工藝講堂皆免費報名，一律採線上報名。報名網址：https://event.culture.tw/NTCRI/\r\n\r\n(二)依據個資法，報名所填寫之個人資料，僅限本活動使用。\r\n\r\n(三)主辦單位保有最終修改、變更、活動解釋及取消本活動、審核報名資格之最終權利；活動內容如有任何變更，將統一公告於臺北當代工藝設計分館官網，恕不另行個別通知。\r\n\r\n六、本中心因應疫情狀況，實施室內容留人數控管自110年7月27日(二)起暫時調整入館方式。\r\n\r\n       請講座報名成功者，請於參加講座前一日完成本館參觀預約。\r\n\r\n      來館預約網址：https://event.culture.tw/NTCRI/portal/ArtistSpace/R0501MAction\r\n\r\n七、為避免聚集，請您依預約日期至本館辦理入場。入場時須出示預約完成確認信及防疫簡訊實聯制畫面。\r\n\r\n八、為維護其他觀眾權益及館內參觀品質，取消參觀者，請於參觀前一天上網取消或來電告知。\r\n\r\n \r\n\r\n \r\n\r\n \r\n\r\n\r\n ',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/NTCRI_11533/2403e501865eb2c145930e39f706b3cf549becd3.jpg',
          masterUnit: [
            '國立台灣工藝研究發展中心',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/NTCRI/portal/Registration/C0103MAction?actId\u003d11533',
          sourceWebPromote: 'https://event.culture.tw/NTCRI',
          comment: '',
          editModifyDate: '2021/09/01 09:22:35',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/08/14',
          endDate: '2021/10/23',
          hitRate: 64,
        },
        {
          version: '1.4',
          UID: '61278379d083a31df0012d7c',
          title: '2021走讀臺灣【尋美．城南】',
          category: '7',
          showInfo: [
            {
              time: '2021/09/18 10:00:00',
              location: '',
              locationName: 'Google Meet 線上教室',
              onSales: 'Y',
              price: '0',
              latitude: null,
              longitude: null,
              endTime: '2021/09/18 10:00:00',
            },
            {
              time: '2021/09/26 14:00:00',
              location: '',
              locationName: 'Google Meet 線上教室',
              onSales: 'Y',
              price: '0',
              latitude: null,
              longitude: null,
              endTime: '2021/09/26 14:00:00',
            },
            {
              time: '2021/10/09 09:00:00',
              location: '',
              locationName: '城南地區',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/10/09 09:00:00',
            },
            {
              time: '2021/10/17 09:00:00',
              location: '',
              locationName: '城南地區',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/10/17 09:00:00',
            },
            {
              time: '2021/10/23 09:00:00',
              location: '',
              locationName: '南海學園',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/10/23 09:00:00',
            },
            {
              time: '2021/10/30 09:00:00',
              location: '',
              locationName: '南海學園',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/10/30 09:00:00',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '2021年國立歷史博物館延續「城南何趣」數位學習資源，從館藏連結藝術和美感，打造「尋美·城南」走讀路徑，邀請民眾藉由走讀、閱讀、解讀三讀體驗，一起在城南歷史空間裡尋美景﹅品美感﹅養美學。歡迎18歲以上對藝術走讀有興趣的朋友參加。\r\n\r\n \r\n\r\n線上講座\r\n\r\n● 線上講座（一）/ 城南的藝術風景\r\n簡介：由深耕城南文史多年的周得豪老師，以典藏城南的概念，介紹舊城南、公館聚落的形成，以及1960年到近代公共\r\n        藝術的演變。\r\n\r\n● 線上講座（二）/「城南．藝術．故事 ─ 南海學園的藝文榮光\r\n簡介：由蕭瓊瑞老師以臺灣美術史的深厚功力和幽默風趣帶領大家跟著藝術家的腳步，一起走進南海學園的藝文榮光。\r\n\r\n \r\n\r\n走讀活動\r\n\r\n● 走讀活動（一）/ 尋美˙城南—看見城南藝術風景\r\n簡介：從城南範圍的中段位置出發，往北經過客家文化園區、城南水岸、同安街/紀州庵和古亭捷運站，認識客家族群移\r\n        居城南背景下的原鄉記憶作品創作，再經過城南水岸回望各個時代文人、藝術家在岸邊描繪與書寫的城南風景。往\r\n        南經過溫羅汀、公館巷弄、溫州公園、台電大樓、寶藏巖藝術村，看見戰後書店匯聚下的生活氛圍與   藝術家呈\r\n        現的當代作品。\r\n\r\n路徑1：捷運台電大樓站集合→師大路往客家文化園區→古亭河濱公園觀景臺→同安街巷弄→古亭捷運站\r\n路徑2：捷運台電大樓站集合→穿越汀州路進到巷弄→溫州公園-加羅林魚木→台電大樓→穿越羅斯福路到\r\n           台鐵新店線水源地舊址→自來水園區旁單車道→寶藏巖國際藝術村\r\n\r\n \r\n\r\n● 走讀活動（二）/ 尋美˙城南—史博南海藝術散步\r\n簡介：從馬白水筆下的史博館出發，走訪張大千流連的荷花池與荷風閣，一路走出南海學園，向曾經任教建中，也是臺\r\n        展推手的鹽月桃甫老師致敬，再沿南海路逛進臺灣教育會館(二二八國家紀念館)，聆聽臺展三少年—陳進﹅郭雪湖\r\n       ﹅林玉山的創作故事。過了重慶南路，在楊英風美術館前雕塑靜靜佇足，感受藝術家創作的熾熱與溫度。\r\n\r\n路徑：史博館→荷花池→建國中學→二二八國家紀念館→楊英風美術館\r\n\r\n●參考書單\r\n\r\n《臺灣美術史辭典1.0》、《溫州街上有什麼？陳柏言短篇小說集》、《我台北，我街道》》、《街屋台灣》、《城南藝事: 名人畫報文集》、《城之南: 紀州庵與台北文學巷弄》、《無聲畫作有聲詩》、《記憶像鐵軌一樣長》、《台北步登公寓:台北最普遍的住宅類型從何而來》、《台北慢步》、《台北地圖歷史散步》、《翹班小旅行: 臺北邊走邊畫、說走就走，找回一個人旅行的愉悅時光》\r\n\r\n ',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/NMH_11072/992256c5b4cc677e7fb77ad060c8c47bdd26a61e.jpg',
          masterUnit: [
            '國立歷史博物館',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://event.culture.tw/NMH/portal/Registration/C0103MAction?actId\u003d11072',
          sourceWebPromote: 'https://event.culture.tw/NMH',
          comment: '',
          editModifyDate: '2021/09/01 09:32:38',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/18',
          endDate: '2021/10/30',
          hitRate: 56,
        },
        {
          version: '1.4',
          UID: '613c9ba6d083a31df001338c',
          title: '【跨閱百年·嘉義山林】系列活動',
          category: '15',
          showInfo: [
            {
              time: '2021/09/23 19:30:00',
              location: '',
              locationName: '線上',
              onSales: 'Y',
              price: '0',
              latitude: null,
              longitude: null,
              endTime: '2021/09/23 19:30:00',
            },
            {
              time: '2021/09/29 19:30:00',
              location: '600  嘉義市長榮街116號',
              locationName: '洪雅書房',
              onSales: 'Y',
              price: '100',
              latitude: '23.4841924',
              longitude: '120.4541764',
              endTime: '2021/09/29 19:30:00',
            },
            {
              time: '2021/09/30 19:30:00',
              location: '',
              locationName: '線上',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/09/30 19:30:00',
            },
            {
              time: '2021/10/07 19:30:00',
              location: '',
              locationName: '線上',
              onSales: 'Y',
              price: '100',
              latitude: null,
              longitude: null,
              endTime: '2021/10/07 19:30:00',
            },
            {
              time: '2021/10/21 13:00:00',
              location: '600  嘉義市共和路410 號',
              locationName: '玉山旅社集合',
              onSales: 'Y',
              price: '350',
              latitude: '23.4871259',
              longitude: '120.4547393',
              endTime: '2021/10/21 13:00:00',
            },
            {
              time: '2021/10/24 09:00:00',
              location: '600  嘉義市長榮街116號',
              locationName: '洪雅書房集合',
              onSales: 'Y',
              price: '350',
              latitude: '23.4841924',
              longitude: '120.4541764',
              endTime: '2021/10/24 09:00:00',
            },
            {
              time: '2021/10/24 13:30:00',
              location: '600  嘉義市長榮街116號',
              locationName: '洪雅書房',
              onSales: 'Y',
              price: '100',
              latitude: '23.4841924',
              longitude: '120.4541764',
              endTime: '2021/10/24 13:30:00',
            },
            {
              time: '2021/10/30 09:00:00',
              location: '600  嘉義市長榮街116號',
              locationName: '洪雅書房集合',
              onSales: 'Y',
              price: '350',
              latitude: '23.4841924',
              longitude: '120.4541764',
              endTime: '2021/10/30 09:00:00',
            },
            {
              time: '2021/11/07 09:00:00',
              location: '600  嘉義市長榮街116號',
              locationName: '洪雅書房集合',
              onSales: 'Y',
              price: '350',
              latitude: '23.4841924',
              longitude: '120.4541764',
              endTime: '2021/11/07 09:00:00',
            },
          ],
          showUnit: '嘉義市洪雅文化協會',
          discountInfo: '',
          descriptionFilterHtml: '★線上活動 (單場次100元)：\r\n\r\n◆ 9/23(四)19:30-21:00「跨閱百年·嘉義山林」行前讀書會─余國信老師(試聽場，免費)\r\n介紹活動外，透過共同閱讀《檜意山林-阿里山林業百年的故事》，由阿里山下的諸羅演義，到阿里山林場、森林鐵道，有系統的認識嘉義重要的百年林業及因阿里山林鐵展開的百年木都。\r\n* 會輪流閱讀，記得打開你的視訊跟麥克風唷！\r\n\r\n◆ 9/30(四)19:30-21:30「百年建築眼」講座─許勝發老師\r\n由國立台北藝術大學建築與文化資產研究所助理教授許勝發老師，介紹嘉義的重要建築。\r\n\r\n◆ 10/7(四)19:30-21:30「林業生態觀」講座─許勝發、江季翰老師\r\n由國立台北藝術大學建築與文化資產研究所助理教授許勝發，與荒野保護協會荒野保護協會雲林分會前分會長江季翰，根據長年觀察，介紹阿里山林業、林相及生態。\r\n\r\n\r\n★ 實體講座 (單場次100元)：@洪雅書房\r\n\r\n◆9/29(三)19:30-21:30「百年林鐵史」講座─許乃懿老師\r\n由鐵道達人許乃懿醫師，從林業的角度看鐵路，深入淺出介紹鐵路、蒸汽火車及中興號。\r\n\r\n◆10/24(三)13:30-15:30「百工職人傳」講座─施志明老師\r\n邀請大新工藝社神桌職人─施志明，從木業到木職人，神桌工藝職人的秘辛大公開。\r\n\r\n\r\n★ 實體走讀活動(單場次350元)：\r\n\r\n◆10/21(四)13:00-16:00 檜村時代─建築x學習(適合小三-小五)(步行)\r\n─余國信、孫崇傑、徐佳伶老師\r\n北門驛集合→行前說明→北門驛→玉山旅社→檜意森活村→澡堂建築→營林俱樂部→所長宿舍→回玉山旅社手作\r\n\r\n◆10/24(日)9:00-15:30木業風華─產業x職人+(成人)(自備交通工具) +「百工職人傳」講座─施志明老師\r\n─余國信、顏朝順、徐佳伶老師\r\n9:00-12:00\r\n洪雅書房集合→行前講座→北香湖→獸魂碑→順益木業→職人開講→杉池\r\n13:30-15:30「百工職人傳」講座─施志明老師\r\n邀請大新工藝社神桌職人─施志明，從木業到木職人，神桌工藝職人的秘辛大公開\r\n\r\n◆10/30(六)9:00-12:00林場風清─散步x生態(親子)(騎乘YouBike後步行)\r\n─許愫真、江季翰、余國信老師\r\n洪雅書房集合→行前講座→樹木園→回洪雅書房討論\r\n\r\n◆11/7(日)9:00-12:00百年鐵道─鐵車x火車司機(皆可)(步行)\r\n─許乃懿、余國信、翁幸昭、江季翰老師\r\n洪雅書房集合→行前講座→林管處→阿里山森林鐵路車庫園區→回洪雅書房討論\r\n\r\n★ 走讀主題書展(自由參加)\r\n9/20-10/10「日本時代的台灣」\r\n10/20-11/10「跨閱百年·嘉義山林」\r\n ',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/488e1f59-86c4-4bf5-8de2-44134f36b915/READTAIWAN_10044/7b2231234d44307c49d245d5f20b3f9036e56b91.jpg',
          masterUnit: [
            '走讀臺灣',
          ],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://docs.google.com/forms/d/e/1FAIpQLSc8gK5cIrEeOMK0yCItMR82kKgbbc4Sl7-BIhgiVn7KWaHXLw/viewform?fbzx\u003d-8463771978985504939',
          sourceWebPromote: 'http://event.culture.tw/READTAIWAN',
          comment: '',
          editModifyDate: '2021/09/13 11:22:11',
          sourceWebName: '藝文活動報名平台',
          startDate: '2021/09/23',
          endDate: '2021/11/07',
          hitRate: 15,
        },
        {
          version: '1.4',
          UID: '5e05c90bd083a31bb0c56552',
          title: '🌾從基礎刺繡到進階立體刺繡，此刻的煦色韶光：線上課程',
          category: '7',
          showInfo: [
            {
              time: '2020/01/01 00:00:00',
              location: '臺北市松山區復興北路231巷19號4樓',
              locationName: '全台灣、不限時間地點，均可觀看',
              onSales: 'Y',
              price: '2340',
              latitude: '25.057251',
              longitude: '121.545857',
              endTime: '2022/01/01 23:59:59',
            },
          ],
          showUnit: '',
          discountInfo: '',
          descriptionFilterHtml: '\r\n\r\n\r\n\r\n初學刺繡的你，開始能將圖畫轉為針法表現，\r\n已有基礎的同學，可以進階的立體型針法\u0026立體刺繡，豐富創作。\r\n教學風格為紮根基底的邏輯引導學習，\r\n讓來參與課程的同學，日後也能靈活運用，\r\n創作自己的圖像，目前累積100多場的實體教學，\r\n從教學經驗裡，集結初學常見問題，以簡單清晰的方式講解。\r\n\r\n\r\n帶領同學進入刺繡yoga，體驗刺繡的時間，\r\n在幾個呼吸的專注裡，都是煦色韶光。\r\n\r\n🦄集結2門實體課程內容，基礎＋進階\r\n🧵　從零開始，循序漸進。\r\n🧵　基礎刺繡觀念：工具、線材使用要領。\r\n🧵　針法教學，詳細解說15種針法\u0026特性。（包含2個解鎖單元針法）\r\n🧵　製作增加層次感的「立體刺繡」\r\n🧵　刺繡於日常：繡品裱框、刺繡在衣物、製成飾品的技巧\r\n\r\n\r\n刺繡的美在於細微：分享使線條表現美好的技巧、\r\n需要注意的細節，日後能將針法靈活運用，\r\n發揮在自己喜歡的圖像上，「針法雖然是固定，但創作是自由的」\r\n\r\n\r\n🧵本課程以花圈示範，\r\n串連起13種針法\u0026立體刺繡教學，\r\n並提供花圈圖稿，每朵花都能成為一個獨立的小作品/飾品。\r\n學會針法原理後，\r\n不限於花，任何圖案都能用刺繡表現。\r\n\r\n\r\n\r\n完全無刺繡經驗的同學也能輕鬆參與課程，\r\n可依需求加購，\r\n本課程的工具材料包：\r\n𝓐基本工具組\r\n-----------\r\n課程會提供講義下載：\r\n1.花圈圖稿、\r\n2.立體刺繡花寶與兔吱圖稿、\r\n3.範本的繡線色號、\r\n同學可依喜好決定圖稿的尺寸大小與配色。\r\n\r\n\r\n\r\n\r\n🧵共八個章節，分為四項主題：\r\n從﹝基礎觀念﹞到﹝針法學習\u0026運用﹞、\r\n﹝立體刺繡製作﹞，\r\n﹝完成自己的刺繡作品﹞。\r\n\r\n\r\n主題1.基礎觀念\r\n初學刺繡若能建立好的觀念，\r\n日後在變化運用時，就能更得心應手。\r\n▸ 認識工具：如何將圖稿描繪到布面、繡框對於刺繡的影響、刺繡針的規格等。\r\n▸ 認識線材：怎麼決定使用幾股繡線呢？線材的特性等。\r\n▸ 針法學習：刺繡的美在於細微：掌控技巧、拉力控制、需要注意的地方等。\r\n▸ 繡圖順序：規劃一幅圖的刺繡順序，提升精緻度。\r\n\r\n\r\n🧵無刺繡經驗的同學，\r\n至少學過﹝章節2-輪廓繡\u0026緞面繡﹞，\r\n再跳著學習其他針法喔！\r\n\r\n\r\n主題2.針法教學\u0026靈活運用課程以花圈繡圖串起13種針法，每一朵花，分別使用了3~5種針法：\r\n\r\n\r\n▸ 13種針法，即能創造豐富層次的紋理表現，\r\n包括：線條、填滿、裝飾、進階-半立體型針法。\r\n▸ 分享每個針法，讓繡線表情更美好的技巧，針法表現up！\r\n\r\n\r\n🧵針法學了之後，可以怎麼運用呢？　以﹝2-1單元輪廓繡﹞為例：\r\n常用來表現「線條」的輪廓繡，\r\n也可填滿面積，還會產生毛流的效果，\r\n是刺繡創作裡最有趣的地方之一。\r\n\r\n\r\n\r\n主題3.立體刺繡製作讓原本平面的刺繡，成為一個獨立的物件，\r\n教導同學如何幫刺繡加上支架，\r\n最後修飾邊緣，讓繡品更精緻，\r\n若再與手工藝材料：例如胸針底座、墜飾等，\r\n組合後就能完成一個刺繡飾品。\r\n▸ 立體刺繡的製作過程\r\n▸ 如何以立體刺繡完成飾品（以花朵胸針為範例）\r\n🧵影片中的花瓣、兔子耳朵，即是立體刺繡\r\n\r\n\r\n主題4.刺繡用於日常\r\n集結同學們最常詢問的問題：\r\n▸ 刺繡飾品製作（胸針、耳環）\r\n▸ 繡品完成後如何裱框。\r\n▸ 刺繡在衣服，需要注意的細節，如何保養。\r\n\r\n\r\n🧵這門課適合\r\n▸ 對刺繡\u0026手作有興趣，無經驗可從零開始。\r\n▸理解針法邏輯，靈活運用在自己的圖像上。\r\n▸對立體刺繡有興趣。▸喜歡依自己步調，調整學習節奏。\r\n▸ 喜歡從無到有，享受創作，感受美的你。\r\n\r\n\r\n作品集\r\n欣賞同學們作品同樣的針法\u0026圖稿，卻各自精彩。\r\n針法是固定，創作是自由的\r\n\r\n\r\n\r\n\r\n\r\n第14種針法～紋理感up：錫蘭繡\r\n第15種針法～紋理感up：結粒纜繩繡\r\n\r\n\r\n\r\n\r\n\r\n\r\n🧵小朋友適合學習嗎？\r\n可以的，課程講解簡單清晰，也適合小朋友學習，建議9歲以上，當然還是依家長評估喔。\r\n🧵線上課程有販售材料包嗎？\r\n有的，可woyi@woyiembroidery.com登記\r\n\r\n\r\n🧵有推薦的工具材料購買點嗎？\r\n有的，於課程公告處提供購買清單。\r\n\r\n\r\n\r\n🧵作業批改方式\r\n請提供照片：至少正拍一張，側拍一張，老師會再給予指導。\r\n🧵回答問題的頻率\r\n若有時間會盡快回覆同學的疑問，最晚1週內回覆。\r\n🧵批改作業的頻率\r\n若有時間會盡快批改同學作業，最晚2週內回覆。\r\n\r\n',
          imageUrl: 'https://cloud.culture.tw/e_new_upload/task/eb7556a1-dbeb-4569-a886-2193d75b55a3/15814/395edb6c0b4a85293a57d2b27d10abbc573b36fa.jpg',
          masterUnit: [],
          subUnit: [],
          supportUnit: [],
          otherUnit: [],
          webSales: 'https://hahow.in/cr/woyiembroidery',
          sourceWebPromote: '',
          comment: '',
          editModifyDate: '2021/09/01 09:23:03',
          sourceWebName: '臺北市政府文化局文化快遞網站',
          startDate: '2020/01/01',
          endDate: '2022/01/01',
          hitRate: 6835,
        },
      ],
    };
  },
};
</script>

<style scoped>
.note{
  background: antiquewhite;
  padding: inherit;
}
</style>
